--Table 1
CREATE OR REPLACE TABLE ASSETS (
    RECORD_TYPE                           VARCHAR(20)   COMMENT 'RECORD TYPE CODE - ALWAYS ASSET',
    FORM_TYPE_CD                          VARCHAR(20)   COMMENT 'TEC FORM USED',
    SCHED_FORM_TYPE_CD                    VARCHAR(20)   COMMENT 'TEC SCHEDULE USED',
    REPORT_INFO_IDENT                     NUMBER(11, 0) COMMENT 'UNIQUE REPORT #',
    RECEIVED_DT                           DATE          COMMENT 'DATE REPORT RECEIVED BY TEC',
    INFO_ONLY_FLAG                        VARCHAR(1)    COMMENT 'SUPERSEDED BY OTHER REPORT',
    FILER_IDENT                           VARCHAR(100)  COMMENT 'FILER ACCOUNT #',
    FILER_TYPE_CD                         VARCHAR(30)   COMMENT 'TYPE OF FILER',
    FILER_NAME                            VARCHAR(200)  COMMENT 'FILER NAME',
    ASSET_INFO_ID                         NUMBER(11, 0) COMMENT 'ASSET UNIQUE IDENTIFIER',
    ASSET_DESCR                           VARCHAR(100)  COMMENT 'DESCRIPTION OF ASSET'
)
COMMENT = 'Assets - Schedule M - Assets valued at $500 or more for judicial filers only. File: assets.csv'
;

COPY INTO ASSETS
FROM @RAW_FILES/assets.csv.gz
FILE_FORMAT = CSV_FILES;



-- Table 2: CandidateData
CREATE OR REPLACE TABLE CANDIDATES (
    RECORD_TYPE                           VARCHAR(20)   COMMENT 'Record type code - always CAND',
    FORM_TYPE_CD                          VARCHAR(20)   COMMENT 'TEC form used',
    SCHED_FORM_TYPE_CD                    VARCHAR(20)   COMMENT 'TEC Schedule Used',
    REPORT_INFO_IDENT                     NUMBER(11, 0) COMMENT 'Unique report #',
    RECEIVED_DT                           DATE          COMMENT 'Date report received by TEC',
    INFO_ONLY_FLAG                        VARCHAR(1)    COMMENT 'Superseded by other report',
    FILER_IDENT                           VARCHAR(100)  COMMENT 'Filer account #',
    FILER_TYPE_CD                         VARCHAR(30)   COMMENT 'Type of filer',
    FILER_NAME                            VARCHAR(200)  COMMENT 'Filer name',
    EXPEND_INFO_ID                        NUMBER(11, 0) COMMENT 'Expenditure unique identifier',
    EXPEND_PERS_ENT_ID                    NUMBER(11, 0) COMMENT 'Candidate unique identifier',
    EXPEND_DT                             DATE          COMMENT 'Expenditure date',
    EXPEND_AMOUNT                         FLOAT         COMMENT 'Expenditure amount',
    EXPEND_DESCR                          VARCHAR(100)  COMMENT 'Expenditure description',
    EXPEND_CAT_CD                         VARCHAR(30)   COMMENT 'Expenditure category code',
    EXPEND_CAT_DESCR                      VARCHAR(100)  COMMENT 'Expenditure category description',
    ITEMIZE_FLAG                          VARCHAR(1)    COMMENT 'Y indicates that the expenditure is itemized',
    POLITICAL_EXPEND_CD                   VARCHAR(30)   COMMENT 'Political expenditure indicator',
    REIMBURSE_INTENDED_FLAG               VARCHAR(1)    COMMENT 'Reimbursement intended indicator',
    SRC_CORP_CONTRIB_FLAG                 VARCHAR(1)    COMMENT 'Expenditure from corporate funds indicator',
    CAPITAL_LIVINGEXP_FLAG                VARCHAR(1)    COMMENT 'Austin living expense indicator',
    CANDIDATE_PERSENT_TYPE_CD             VARCHAR(30)   COMMENT 'Type of candidate name data - INDIVIDUAL or ENTITY',
    CANDIDATE_NAME_ORGANIZATION           VARCHAR(100)  COMMENT 'For ENTITY, the candidate organization name',
    CANDIDATE_NAME_LAST                   VARCHAR(100)  COMMENT 'For INDIVIDUAL, the candidate last name',
    CANDIDATE_NAME_SUFFIX_CD              VARCHAR(30)   COMMENT 'For INDIVIDUAL, the candidate name suffix (e.g. JR, MD, II)',
    CANDIDATE_NAME_FIRST                  VARCHAR(45)   COMMENT 'For INDIVIDUAL, the candidate first name',
    CANDIDATE_NAME_PREFIX_CD              VARCHAR(30)   COMMENT 'For INDIVIDUAL, the candidate name prefix (e.g. MR, MRS, MS)',
    CANDIDATE_NAME_SHORT                  VARCHAR(25)   COMMENT 'For INDIVIDUAL, the candidate short name (nickname)',
    CANDIDATE_HOLD_OFFICE_CD              VARCHAR(30)   COMMENT 'Candidate office held',
    CANDIDATE_HOLD_OFFICE_DISTRICT        VARCHAR(11)   COMMENT 'Candidate office held district',
    CANDIDATE_HOLD_OFFICE_PLACE           VARCHAR(11)   COMMENT 'Candidate office held place',
    CANDIDATE_HOLD_OFFICE_DESCR           VARCHAR(100)  COMMENT 'Candidate office held description',
    CANDIDATE_HOLD_OFFICE_COUNTY_CD       VARCHAR(5)    COMMENT 'Candidate office held county code',
    CANDIDATE_HOLD_OFFICE_COUNTY_DESCR    VARCHAR(100)  COMMENT 'Candidate office held county description',
    CANDIDATE_SEEK_OFFICE_CD              VARCHAR(30)   COMMENT 'Candidate office sought',
    CANDIDATE_SEEK_OFFICE_DISTRICT        VARCHAR(11)   COMMENT 'Candidate office sought district',
    CANDIDATE_SEEK_OFFICE_PLACE           VARCHAR(11)   COMMENT 'Candidate office sought place',
    CANDIDATE_SEEK_OFFICE_DESCR           VARCHAR(100)  COMMENT 'Candidate office sought description',
    CANDIDATE_SEEK_OFFICE_COUNTY_CD       VARCHAR(5)    COMMENT 'Candidate office sought county code',
    CANDIDATE_SEEK_OFFICE_COUNTY_DESCR    VARCHAR(100)  COMMENT 'Candidate office sought county description'
) COMMENT = 'Candidate benefiting from a direct campaign expenditure. A direct campaign expenditure to benefit a candidate is not a political contribution to that candidate. Instead, a direct campaign expenditure is a campaign expenditure made on someone elses behalf and without the prior consent or approval of that person. A given EXPN record can have zero or more related CAND records. Any CAND  records are written to the file immediately after their related EXPN record. File: cand.csv'
;

COPY INTO CANDIDATES
FROM @RAW_FILES/cand.csv.gz
FILE_FORMAT = CSV_FILES;



--  Table 3: ContributionData
CREATE OR REPLACE TABLE CONTRIBUTIONS (
    RECORD_TYPE                       VARCHAR(20)    COMMENT 'Record type code - always RCPT',
    FORM_TYPE_CD                      VARCHAR(20)    COMMENT 'TEC form used',
    SCHED_FORM_TYPE_CD                VARCHAR(20)    COMMENT 'TEC Schedule Used',
    REPORT_INFO_IDENT                 NUMBER(11, 0)  COMMENT 'Unique report #',
    RECEIVED_DT                       DATE           COMMENT 'Date report received by TEC',
    INFO_ONLY_FLAG                    VARCHAR(1)     COMMENT 'Superseded by other report',
    FILER_IDENT                       VARCHAR(100)   COMMENT 'Filer account #',
    FILER_TYPE_CD                     VARCHAR(30)    COMMENT 'Type of filer',
    FILER_NAME                        VARCHAR(200)   COMMENT 'Filer name',
    CONTRIBUTION_INFO_ID              NUMBER(11, 0)  COMMENT 'Contribution unique identifier',
    CONTRIBUTION_DT                   Date           COMMENT 'Contribution date',
    CONTRIBUTION_AMOUNT               FLOAT          COMMENT 'Contribution amount',
    CONTRIBUTION_DESCR                VARCHAR(100)   COMMENT 'Contribution description',
    ITEMIZE_FLAG                      VARCHAR(1)     COMMENT 'Y indicates that the contribution is itemized',
    TRAVEL_FLAG                       VARCHAR(1)     COMMENT 'Y indicates that the contribution has associated travel',
    CONTRIBUTOR_PERSENT_TYPE_CD       VARCHAR(30)    COMMENT 'Type of contributor name data - INDIVIDUAL or ENTITY',
    CONTRIBUTOR_NAME_ORGANIZATION     VARCHAR(100)   COMMENT 'For ENTITY, the contributor organization name',
    CONTRIBUTOR_NAME_LAST             VARCHAR(100)   COMMENT 'For INDIVIDUAL, the contributor last name',
    CONTRIBUTOR_NAME_SUFFIX_CD        VARCHAR(30)    COMMENT 'For INDIVIDUAL, the contributor name suffix (e.g. JR, MD, II)',
    CONTRIBUTOR_NAME_FIRST            VARCHAR(45)    COMMENT 'For INDIVIDUAL, the contributor first name',
    CONTRIBUTOR_NAME_PREFIX_CD        VARCHAR(30)    COMMENT 'For INDIVIDUAL, the contributor name prefix (e.g. MR, MRS, MS)',
    CONTRIBUTOR_NAME_SHORT            VARCHAR(25)    COMMENT 'For INDIVIDUAL, the contributor short name (nickname)',
    CONTRIBUTOR_STREET_CITY           VARCHAR(30)    COMMENT 'Contributor street address - city',
    CONTRIBUTOR_STREET_STATE_CD       VARCHAR(20)    COMMENT 'Contributor street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    CONTRIBUTOR_STREET_COUNTY_CD      VARCHAR(5)     COMMENT 'Contributor street address - Texas county',
    CONTRIBUTOR_STREET_COUNTRY_CD     VARCHAR(3)     COMMENT 'Contributor street address - country (e.g. USA, UMI, MEX, CAN)',
    CONTRIBUTOR_STREET_POSTAL_CODE    VARCHAR(20)    COMMENT 'Contributor street address - postal code - for USA addresses only',
    CONTRIBUTOR_STREET_REGION         VARCHAR(30)    COMMENT 'Contributor street address - region for country other than USA',
    CONTRIBUTOR_EMPLOYER              VARCHAR(60)    COMMENT 'Contributor employer',
    CONTRIBUTOR_OCCUPATION            VARCHAR(60)    COMMENT 'Contributor occupation',
    CONTRIBUTOR_JOB_TITLE             VARCHAR(60)    COMMENT 'Contributor job title',
    CONTRIBUTOR_PAC_FEIN              VARCHAR(12)    COMMENT 'FEC ID of out-of-state PAC contributor',
    CONTRIBUTOR_OOS_PAC_FLAG          VARCHAR(1)     COMMENT 'Indicates if contributor is an out-of-state PAC',
    CONTRIBUTOR_LAWFIRM_NAME          VARCHAR(60)    COMMENT 'Contributor law firm name',
    CONTRIBUTOR_SPOUSE_LAWFIRM_NAME   VARCHAR(60)    COMMENT 'Contributor spouse law firm name',
    CONTRIBUTOR_PARENT1_LAWFIRM_NAME  VARCHAR(60)    COMMENT 'Contributor parent #1 law firm name',
    CONTRIBUTOR_PARENT2_LAWFIRM_NAME  VARCHAR(60)    COMMENT 'Contributor parent #2 law firm name',
    SOURCE_FILE_NAME                  VARCHAR(100)   COMMENT 'Name of source file, as found in the internal stage'
) COMMENT = 'Contributions - Schedules A/C - Contributions from special session and special pre-election (formerly Telegram) reports are stored in the file cont_ss and cont_t. These records are kept separate from the contribs files to avoid creating duplicates, because they are supposed to be re-reported on the next regular campaign finance report. Files: contribs_##.csv'
;

COPY INTO CONTRIBUTIONS
FROM
    (
    SELECT 
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21,
        $22,
        $23,
        $24,
        $25,
        $26,
        $27,
        $28,
        $29,
        $30,
        $31,
        $32,
        $33,
        $34,
        $35,
        $36,
        $37,
        METADATA$FILENAME
        FROM @RAW_FILES)
FILE_FORMAT = CSV_FILES
PATTERN = 'contribs_.*[.]csv[.]gz';


--  Table 4: ContributionTData
CREATE OR REPLACE TABLE CONTRIBUTIONS_PRE_ELECTION (
    RECORD_TYPE                       VARCHAR(20)       COMMENT 'Record type code - always RCPT',
    FORM_TYPE_CD                      VARCHAR(20)       COMMENT 'TEC form used',
    SCHED_FORM_TYPE_CD                VARCHAR(20)       COMMENT 'TEC Schedule Used',
    REPORT_INFO_IDENT                 NUMBER(11, 0)     COMMENT 'Unique report #',
    RECEIVED_DT                       DATE              COMMENT 'Date report received by TEC',
    INFO_ONLY_FLAG                    VARCHAR(1)        COMMENT 'Superseded by other report',
    FILER_IDENT                       VARCHAR(100)      COMMENT 'Filer account #',
    FILER_TYPE_CD                     VARCHAR(30)       COMMENT 'Type of filer',
    FILER_NAME                        VARCHAR(200)      COMMENT 'Filer name',
    CONTRIBUTION_INFO_ID              NUMBER(11, 0)     COMMENT 'Contribution unique identifier',
    CONTRIBUTION_DT                   Date              COMMENT 'Contribution date',
    CONTRIBUTION_AMOUNT               FLOAT             COMMENT 'Contribution amount',
    CONTRIBUTION_DESCR                VARCHAR(100)      COMMENT 'Contribution description',
    ITEMIZE_FLAG                      VARCHAR(1)        COMMENT 'Y indicates that the contribution is itemized',
    TRAVEL_FLAG                       VARCHAR(1)        COMMENT 'Y indicates that the contribution has associated travel',
    CONTRIBUTOR_PERSENT_TYPE_CD       VARCHAR(30)       COMMENT 'Type of contributor name data - INDIVIDUAL or ENTITY',
    CONTRIBUTOR_NAME_ORGANIZATION     VARCHAR(100)      COMMENT 'For ENTITY, the contributor organization name',
    CONTRIBUTOR_NAME_LAST             VARCHAR(100)      COMMENT 'For INDIVIDUAL, the contributor last name',
    CONTRIBUTOR_NAME_SUFFIX_CD        VARCHAR(30)       COMMENT 'For INDIVIDUAL, the contributor name suffix (e.g. JR, MD, II)',
    CONTRIBUTOR_NAME_FIRST            VARCHAR(45)       COMMENT 'For INDIVIDUAL, the contributor first name',
    CONTRIBUTOR_NAME_PREFIX_CD        VARCHAR(30)       COMMENT 'For INDIVIDUAL, the contributor name prefix (e.g. MR, MRS, MS)',
    CONTRIBUTOR_NAME_SHORT            VARCHAR(25)       COMMENT 'For INDIVIDUAL, the contributor short name (nickname)',
    CONTRIBUTOR_STREET_CITY           VARCHAR(30)       COMMENT 'Contributor street address - city',
    CONTRIBUTOR_STREET_STATE_CD       VARCHAR(20)       COMMENT 'Contributor street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    CONTRIBUTOR_STREET_COUNTY_CD      VARCHAR(5)        COMMENT 'Contributor street address - Texas county',
    CONTRIBUTOR_STREET_COUNTRY_CD     VARCHAR(3)        COMMENT 'Contributor street address - country (e.g. USA, UMI, MEX, CAN)',
    CONTRIBUTOR_STREET_POSTAL_CODE    VARCHAR(20)       COMMENT 'Contributor street address - postal code - for USA addresses only',
    CONTRIBUTOR_STREET_REGION         VARCHAR(30)       COMMENT 'Contributor street address - region for country other than USA',
    CONTRIBUTOR_EMPLOYER              VARCHAR(60)       COMMENT 'Contributor employer',
    CONTRIBUTOR_OCCUPATION            VARCHAR(60)       COMMENT 'Contributor occupation',
    CONTRIBUTOR_JOB_TITLE             VARCHAR(60)       COMMENT 'Contributor job title',
    CONTRIBUTOR_PAC_FEIN              VARCHAR(12)       COMMENT 'FEC ID of out-of-state PAC contributor',
    CONTRIBUTOR_OOS_PAC_FLAG          VARCHAR(1)        COMMENT 'Indicates if contributor is an out-of-state PAC',
    CONTRIBUTOR_LAWFIRM_NAME          VARCHAR(60)       COMMENT 'Contributor law firm name',
    CONTRIBUTOR_SPOUSE_LAWFIRM_NAME   VARCHAR(60)       COMMENT 'Contributor spouse law firm name',
    CONTRIBUTOR_PARENT1_LAWFIRM_NAME  VARCHAR(60)       COMMENT 'Contributor parent #1 law firm name',
    CONTRIBUTOR_PARENT2_LAWFIRM_NAME  VARCHAR(60)       COMMENT 'Contributor parent #2 law firm name',
    SOURCE_FILE_NAME                  VARCHAR(100)      COMMENT 'Name of source file, as found in the internal stage'
) COMMENT = 'Contributions - Schedules A/C - Contributions from special session and special pre-election (formerly Telegram) reports are stored in the file cont_ss and cont_t. These records are kept separate from the contribs files to avoid creating duplicates, because they are supposed to be re-reported on the next regular campaign finance report. Files: contribs_##.csv'
;

COPY INTO CONTRIBUTIONS_PRE_ELECTION
FROM
    (
    SELECT 
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21,
        $22,
        $23,
        $24,
        $25,
        $26,
        $27,
        $28,
        $29,
        $30,
        $31,
        $32,
        $33,
        $34,
        $35,
        $36,
        $37,
        METADATA$FILENAME
        FROM @RAW_FILES/cont_t.csv.gz)
FILE_FORMAT = CSV_FILES;



--Table 5: 
CREATE OR REPLACE TABLE TOTALS_COVER_SHEET_1 (
    RECORD_TYPE                       VARCHAR(20)    COMMENT 'Record type code - always CVR1',
    FORM_TYPE_CD                      VARCHAR(20)    COMMENT 'TEC form used',
    REPORT_INFO_IDENT                 NUMBER(11, 0)  COMMENT 'Unique report #',
    RECEIVED_DT                       DATE           COMMENT 'Date report received by TEC',
    INFO_ONLY_FLAG                    VARCHAR(1)     COMMENT 'Superseded by other report',
    FILER_IDENT                       VARCHAR(100)   COMMENT 'Filer account #',
    FILER_TYPE_CD                     VARCHAR(30)    COMMENT 'Type of filer',
    FILER_NAME                        VARCHAR(200)   COMMENT 'Filer name',
    REPORT_TYPE_CD1                   VARCHAR(30)    COMMENT 'Report type covered',
    REPORT_TYPE_CD2                   VARCHAR(30)    COMMENT 'Report type covered',
    REPORT_TYPE_CD3                   VARCHAR(30)    COMMENT 'Report type covered',
    REPORT_TYPE_CD4                   VARCHAR(30)    COMMENT 'Report type covered',
    REPORT_TYPE_CD5                   VARCHAR(30)    COMMENT 'Report type covered',
    REPORT_TYPE_CD6                   VARCHAR(30)    COMMENT 'Report type covered',
    REPORT_TYPE_CD7                   VARCHAR(30)    COMMENT 'Report type covered',
    REPORT_TYPE_CD8                   VARCHAR(30)    COMMENT 'Report type covered',
    REPORT_TYPE_CD9                   VARCHAR(30)    COMMENT 'Report type covered',
    REPORT_TYPE_CD10                  VARCHAR(30)    COMMENT 'Report type covered',
    SOURCE_CATEGORY_CD                VARCHAR(30)    COMMENT 'Source of report (ELECTRONIC, KEYED)',
    DUE_DT                            DATE           COMMENT 'Report due date',
    FILED_DT                          DATE           COMMENT 'Date report was filed (postmark)',
    PERIOD_START_DT                   DATE           COMMENT 'Beginning of period covered',
    PERIOD_END_DT                     DATE           COMMENT 'Ending of period covered',
    UNITEMIZED_CONTRIB_AMOUNT         FLOAT          COMMENT 'Total unitemized political contribs',
    TOTAL_CONTRIB_AMOUNT              FLOAT          COMMENT 'Total political contribs',
    UNITEMIZED_EXPEND_AMOUNT          FLOAT          COMMENT 'Total unitemized political expend below threshold',
    TOTAL_EXPEND_AMOUNT               FLOAT          COMMENT 'Total political expend',
    LOAN_BALANCE_AMOUNT               FLOAT          COMMENT 'Total principal amount of all outstanding loans as of the last day of the reporting period',
    CONTRIBS_MAINTAINED_AMOUNT        FLOAT          COMMENT 'Total contributions maintained as of the last day of the reporting period',
    UNITEMIZED_PLEDGE_AMOUNT          FLOAT          COMMENT 'Total unitemized pledges',
    UNITEMIZED_LOAN_AMOUNT            FLOAT          COMMENT 'Total unitemized loans',
    TOTAL_INTEREST_EARNED_AMOUNT      FLOAT          COMMENT 'Total amount of interest and other income earned on unexpended political contributions during the previous year',
    ELECTION_DT                       DATE           COMMENT 'Election date',
    ELECTION_TYPE_CD                  VARCHAR(30)    COMMENT 'Election type (PRIMARY, GENERAL, etc)',
    ELECTION_TYPE_DESCR               VARCHAR(100)   COMMENT 'Election type description (electionTypeCd=OTHER)',
    NO_ACTIVITY_FLAG                  VARCHAR(1)     COMMENT 'No activity indicator',
    POLITICAL_PARTY_CD                VARCHAR(30)    COMMENT 'Political party (DEM, REP, LIB, etc)',
    POLITICAL_DIVISION_CD             VARCHAR(30)    COMMENT 'Political division (STATE, COUNTY, etc)',
    POLITICAL_PARTY_OTHER_DESCR       VARCHAR(100)   COMMENT 'Political party description (politicalPartyCd=OTHER)',
    POLITICAL_PARTY_COUNTY_CD         VARCHAR(30)    COMMENT 'Political party county',
    TIMELY_CORRECTION_FLAG            VARCHAR(1)     COMMENT 'Correction aff timely indicator',
    SEMIANNUAL_CHECKBOX_FLAG          VARCHAR(1)     COMMENT 'Correction aff semiannual indicator',
    HIGH_CONTRIB_THRESHHOLD_CD        VARCHAR(30)    COMMENT 'High itemization threshold indicator',
    SOFTWARE_RELEASE                  VARCHAR(20)    COMMENT 'Software release (version)',
    INTERNET_VISIBLE_FLAG             VARCHAR(1)     COMMENT 'Internet visible indicator',
    SIGNER_PRINTED_NAME               VARCHAR(100)   COMMENT 'Document signer name',
    ADDR_CHANGE_FILER_FLAG            VARCHAR(1)     COMMENT 'Filer address change indicator',
    ADDR_CHANGE_TREAS_FLAG            VARCHAR(1)     COMMENT 'Treasurer address change indicator',
    ADDR_CHANGE_CHAIR_FLAG            VARCHAR(1)     COMMENT 'Chair address change indicator',
    FILER_PERSENT_TYPE_CD             VARCHAR(30)    COMMENT 'Type of filer name data - INDIVIDUAL or ENTITY',
    FILER_NAME_ORGANIZATION           VARCHAR(100)   COMMENT 'For ENTITY, the filer organization name',
    FILER_NAME_LAST                   VARCHAR(100)   COMMENT 'For INDIVIDUAL, the filer last name',
    FILER_NAME_SUFFIX_CD              VARCHAR(30)    COMMENT 'For INDIVIDUAL, the filer name suffix (e.g. JR, MD, II)',
    FILER_NAME_FIRST                  VARCHAR(45)    COMMENT 'For INDIVIDUAL, the filer first name',
    FILER_NAME_PREFIX_CD              VARCHAR(30)    COMMENT 'For INDIVIDUAL, the filer name prefix (e.g. MR, MRS, MS)',
    FILER_NAME_SHORT                  VARCHAR(25)    COMMENT 'For INDIVIDUAL, the filer short name (nickname)',
    FILER_STREET_ADDR1                VARCHAR(55)    COMMENT 'Filer street address - line 1',
    FILER_STREET_ADDR2                VARCHAR(55)    COMMENT 'Filer street address - line 2',
    FILER_STREET_CITY                 VARCHAR(30)    COMMENT 'Filer street address - city',
    FILER_STREET_STATE_CD             VARCHAR(2)     COMMENT 'Filer street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    FILER_STREET_COUNTY_CD            VARCHAR(5)     COMMENT 'Filer street address - Texas county',
    FILER_STREET_COUNTRY_CD           VARCHAR(3)     COMMENT 'Filer street address - country (e.g. USA, UMI, MEX, CAN)',
    FILER_STREET_POSTAL_CODE          VARCHAR(20)    COMMENT 'Filer street address - postal code - for USA addresses only',
    FILER_STREET_REGION               VARCHAR(30)    COMMENT 'Filer street address - region for country other than USA',
    FILER_HOLD_OFFICE_CD              VARCHAR(30)    COMMENT 'Filer office held',
    FILER_HOLD_OFFICE_DISTRICT        VARCHAR(11)    COMMENT 'Filer office held district',
    FILER_HOLD_OFFICE_PLACE           VARCHAR(11)    COMMENT 'Filer office held place',
    FILER_HOLD_OFFICE_DESCR           VARCHAR(100)   COMMENT 'Filer office held description',
    FILER_HOLD_OFFICE_COUNTY_CD       VARCHAR(5)     COMMENT 'Filer office held country code',
    FILER_HOLD_OFFICE_COUNTY_DESCR    VARCHAR(100)   COMMENT 'Filer office help county description',
    FILER_SEEKOFFICE_CD               VARCHAR(30)    COMMENT 'Filer office sought',
    FILER_SEEK_OFFICE_DISTRICT        VARCHAR(11)    COMMENT 'Filer office sought district',
    FILER_SEEK_OFFICE_PLACE           VARCHAR(11)    COMMENT 'Filer office sought place',
    FILER_SEEK_OFFICE_DESCR           VARCHAR(100)   COMMENT 'Filer office sought description',
    FILER_SEEK_OFFICE_COUNTY_CD       VARCHAR(5)     COMMENT 'Filer office sought county code',
    FILER_SEEK_OFFICE_COUNTY_DESCR    VARCHAR(100)   COMMENT 'Filer office sought county description',
    TREAS_PERSENT_TYPE_CD             VARCHAR(30)    COMMENT 'Type of treasurer name data - INDIVIDUAL or ENTITY',
    TREAS_NAME_ORGANIZATION           VARCHAR(100)   COMMENT 'For ENTITY, the treasurer organization name',
    TREAS_NAME_LAST                   VARCHAR(100)   COMMENT 'For INDIVIDUAL, the treasurer last name',
    TREAS_NAME_SUFFIX_CD              VARCHAR(30)    COMMENT 'For INDIVIDUAL, the treasurer name suffix (e.g. JR, MD, II)',
    TREAS_NAME_FIRST                  VARCHAR(45)    COMMENT 'For INDIVIDUAL, the treasurer first name',
    TREAS_NAME_PREFIX_CD              VARCHAR(30)    COMMENT 'For INDIVIDUAL, the treasurer name prefix (e.g. MR, MRS, MS)',
    TREAS_NAME_SHORT                  VARCHAR(25)    COMMENT 'For INDIVIDUAL, the treasurer short name (nickname)',
    TREAS_STREET_ADDR1                VARCHAR(55)    COMMENT 'Treasurer street address - line 1',
    TREAS_STREET_ADDR2                VARCHAR(55)    COMMENT 'Treasurer street address - line 2',
    TREAS_STREET_CITY                 VARCHAR(30)    COMMENT 'Treasurer street address - city',
    TREAS_STREET_STATE_CD             VARCHAR(2)     COMMENT 'Treasurer street address - state code (e.g. TX, CA) - for country=USA/UMI onl',
    TREAS_STREET_COUNTY_CD            VARCHAR(5)     COMMENT 'Treasurer street address - Texas county',
    TREAS_STREET_COUNTRY_CD           VARCHAR(3)     COMMENT 'Treasurer street address - country (e.g. USA, UMI, MEX, CAN)',
    TREAS_STREET_POSTAL_CODE          VARCHAR(20)    COMMENT 'Treasurer street address - postal code - for USA addresses only',
    TREAS_STREET_REGION               VARCHAR(30)    COMMENT 'Treasurer street address - region for country other than USA',
    TREAS_MAILING_ADDR1               VARCHAR(55)    COMMENT 'Treasurer mailing address - line 1',
    TREAS_MAILING_ADDR2               VARCHAR(55)    COMMENT 'Treasurer mailing address - line 2',
    TREAS_MAILING_CITY                VARCHAR(30)    COMMENT 'Treasurer mailing address - city',
    TREAS_MAILING_STATE_CD            VARCHAR(2)     COMMENT 'Treasurer mailing address - state code (e.g. TX, CA) - for country=USA/UMI only',
    TREAS_MAILING_COUNTY_CD           VARCHAR(5)     COMMENT 'Treasurer mailing address - Texas county',
    TREAS_MAILING_COUNTRY_CD          VARCHAR(3)     COMMENT 'Treasurer mailing address - country (e.g. USA, UMI, MEX, CAN)',
    TREAS_MAILING_POSTAL_CODE         VARCHAR(20)    COMMENT 'Treasurer mailing address - postal code - USA addresses only',
    TREAS_MAILING_REGION              VARCHAR(30)    COMMENT 'Treasurer mailing address - region for country other than USA',
    TREAS_PRIMARY_USA_PHONE_FLAG      VARCHAR(1)     COMMENT 'Treasurer primary phone number - Y if number is a USA phone, N otherwis',
    TREAS_PRIMARY_PHONE_NUMBER        VARCHAR(20)    COMMENT 'Treasurer primary phone number',
    TREAS_PRIMARY_PHONE_EXT           VARCHAR(10)    COMMENT 'Treasurer primary phone extension',
    CHAIR_PERSENT_TYPE_CD             VARCHAR(30)    COMMENT 'Type of chair name data - INDIVIDUAL or ENTITY',
    CHAIR_NAME_ORGANIZATION           VARCHAR(100)   COMMENT 'For ENTITY, the chair organization name',
    CHAIR_NAME_LAST                   VARCHAR(100)   COMMENT 'For INDIVIDUAL, the chair last name',
    CHAIR_NAME_SUFFIX_CD              VARCHAR(30)    COMMENT 'For INDIVIDUAL, the chair name suffix (e.g. JR, MD, II)',
    CHAIR_NAME_FIRST                  VARCHAR(45)    COMMENT 'For INDIVIDUAL, the chair first name',
    CHAIR_NAME_PREFIX_CD              VARCHAR(30)    COMMENT 'For INDIVIDUAL, the chair name prefix (e.g. MR, MRS, MS)',
    CHAIR_NAME_SHORT                  VARCHAR(25)    COMMENT 'For INDIVIDUAL, the chair short name (nickname)',
    CHAIR_STREET_ADDR1                VARCHAR(55)    COMMENT 'Chair street address - line 1',
    CHAIR_STREET_ADDR2                VARCHAR(55)    COMMENT 'Chair street address - line 2',
    CHAIR_STREET_CITY                 VARCHAR(30)    COMMENT 'Chair street address - city',
    CHAIR_STREET_STATE_CD             VARCHAR(2)     COMMENT 'Chair street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    CHAIR_STREET_COUNTY_CD            VARCHAR(5)     COMMENT 'Chair street address - Texas county',
    CHAIR_STREET_COUNTRY_CD           VARCHAR(3)     COMMENT 'Chair street address - country (e.g. USA, UMI, MEX, CAN)',
    CHAIR_STREET_POSTAL_CODE          VARCHAR(20)    COMMENT 'Chair street address - postal code - for USA addresses only',
    CHAIR_STREET_REGION               VARCHAR(30)    COMMENT 'Chair street address - region for country other than USA',
    CHAIR_MAILINGADDR1                VARCHAR(55)    COMMENT 'Chair mailing address - line 1',
    CHAIR_MAILINGADDR2                VARCHAR(55)    COMMENT 'Chair mailing address - line 2',
    CHAIR_MAILING_CITY                VARCHAR(30)    COMMENT 'Chair mailing address - city',
    CHAIR_MAILING_STATE_CD            VARCHAR(2)     COMMENT 'Chair mailing address - state code (e.g. TX, CA) - for country=USA/UMI onl',
    CHAIR_MAILING_COUNTY_CD           VARCHAR(5)     COMMENT 'Chair mailing address - Texas county',
    CHAIR_MAILING_COUNTRY_CD          VARCHAR(3)     COMMENT 'Chair mailing address - country (e.g. USA, UMI, MEX, CAN)',
    CHAIR_MAILING_POSTAL_CODE         VARCHAR(20)    COMMENT 'Chair mailing address - postal code - USA addresses only',
    CHAIR_MAILING_REGION              VARCHAR(30)    COMMENT 'Chair mailing address - region for country other than USA',
    CHAIR_PRIMARY_USA_PHONE_FLAG      VARCHAR(1)     COMMENT 'Chair primary phone number - Y if number is a USA phone, N otherwis',
    CHAIR_PRIMARY_PHONE_NUMBER        VARCHAR(20)    COMMENT 'Chair primary phone number',
    CHAIR_PRIMARY_PHONE_EXT           VARCHAR(10)    COMMENT 'Chair primary extension'
) COMMENT = 'Cover Sheet 1 - Cover sheet information and totals. cover_ss and cover_t contain cover sheet information for special session reports and special pre-election (formerly Telegram) Reports. Cover sheets for these reports do not contain totals. Files: cover.csv'
;

COPY INTO TOTALS_COVER_SHEET_1
FROM @RAW_FILES/cover.csv.gz
FILE_FORMAT = CSV_FILES;



--Table #6: CoverSheet2Data 
CREATE OR REPLACE TABLE NOTICES_COVER_SHEET_2 (
    RECORD_TYPE                       VARCHAR(20)       COMMENT 'Record type code - always CVR2',
    FORM_TYPE_CD                      VARCHAR(20)       COMMENT 'TEC form used',
    REPORT_INFO_IDENT                 NUMBER(11, 0)     COMMENT 'Unique report #',
    RECEIVED_DT                       DATE              COMMENT 'Date report received by TEC',
    INFO_ONLY_FLAG                    VARCHAR(1)        COMMENT 'Superseded by other report',
    FILER_IDENT                       VARCHAR(100)      COMMENT 'Filer account #',
    FILER_TYPE_CD                     VARCHAR(30)       COMMENT 'Type of filer',
    FILER_NAME                        VARCHAR(200)      COMMENT 'Filer name',
    COMMITTEE_ACTIVITY_ID             NUMBER(11, 0)     COMMENT 'Contribution unique identifier',
    NOTIFIER_COMMACT_PERSENT_KIND_CD  VARCHAR(30)       COMMENT 'Committee activity person/entity kind',
    NOTIFIER_PERSENT_TYPE_CD          VARCHAR(30)       COMMENT 'Type of notifier name data - INDIVIDUAL or ENTITY',
    NOTIFIER_NAME_ORGANIZATION        VARCHAR(100)      COMMENT 'For ENTITY, the notifier organization name',
    NOTIFIER_NAME_LAST                VARCHAR(100)      COMMENT 'For INDIVIDUAL, the notifier last name',
    NOTIFIER_NAME_SUFFIX_CD           VARCHAR(30)       COMMENT 'For INDIVIDUAL, the notifier name suffix (e.g. JR, MD, II)',
    NOTIFIER_NAME_FIRST               VARCHAR(45)       COMMENT 'For INDIVIDUAL, the notifier first name',
    NOTIFIER_NAME_PREFIX_CD           VARCHAR(30)       COMMENT 'For INDIVIDUAL, the notifier name prefix (e.g. MR, MRS, MS)',
    NOTIFIER_NAME_SHORT               VARCHAR(25)       COMMENT 'For INDIVIDUAL, the notifier short name (nickname)',
    NOTIFIER_STREET_ADDR1             VARCHAR(55)       COMMENT 'Notifier street address - line 1',
    NOTIFIER_STREET_ADDR2             VARCHAR(55)       COMMENT 'Notifier street address - line 2',
    NOTIFIER_STREET_CITY              VARCHAR(30)       COMMENT 'Notifier street address - city',
    NOTIFIER_STREET_STATE_CD          VARCHAR(2)        COMMENT 'Notifier street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    NOTIFIER_STREET_COUNTY_CD         VARCHAR(5)        COMMENT 'Notifier street address - Texas county',
    NOTIFIER_STREET_COUNTRY_CD        VARCHAR(3)        COMMENT 'Notifier street address - country (e.g. USA, UMI, MEX, CAN)',
    NOTIFIER_STREET_POSTAL_CODE       VARCHAR(20)       COMMENT 'Notifier street address - postal code - for USA addresses only',
    NOTIFIER_STREET_REGION            VARCHAR(30)       COMMENT 'Notifier street address - region for country other than USA',
    TREAS_PERSENT_TYPE_CD             VARCHAR(30)       COMMENT 'Type of treasurer name data - INDIVIDUAL or ENTITY',
    TREAS_NAME_ORGANIZATION           VARCHAR(100)      COMMENT 'For ENTITY, the treasurer organization name',
    TREAS_NAME_LAST                   VARCHAR(100)      COMMENT 'For INDIVIDUAL, the treasurer last name',
    TREAS_NAME_SUFFIX_CD              VARCHAR(30)       COMMENT 'For INDIVIDUAL, the treasurer name suffix (e.g. JR, MD, II)',
    TREAS_NAME_FIRST                  VARCHAR(45)       COMMENT 'For INDIVIDUAL, the treasurer first name',
    TREAS_NAME_PREFIX_CD              VARCHAR(30)       COMMENT 'For INDIVIDUAL, the treasurer name prefix (e.g. MR, MRS, MS)',
    TREAS_NAME_SHORT                  VARCHAR(25)       COMMENT 'For INDIVIDUAL, the treasurer short name (nickname)',
    TREAS_STREET_ADDR1                VARCHAR(55)       COMMENT 'Treasurer street address - line 1',
    TREAS_STREET_ADDR2                VARCHAR(55)       COMMENT 'Treasurer street address - line 2',
    TREAS_STREET_CITY                 VARCHAR(30)       COMMENT 'Treasurer street address - city',
    TREAS_STREET_STATE_CD             VARCHAR(2)        COMMENT 'Treasurer street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    TREAS_STREET_COUNTY_CD            VARCHAR(5)        COMMENT 'Treasurer street address - Texas county',
    TREAS_STREET_COUNTRY_CD           VARCHAR(3)        COMMENT 'Treasurer street address - country (e.g. USA, UMI, MEX, CAN)',
    TREAS_STREET_POSTAL_CODE          VARCHAR(20)       COMMENT 'Treasurer street address - postal code - for USA addresses only',
    TREAS_STREET_REGION               VARCHAR(30)       COMMENT 'Treasurer street address - region for country other than USA'
) COMMENT = 'Cover Sheet 2 - Notices received by candidates/office holders. These notices are reported at the bottom of Cover Sheet Page 1 and the top of Cover Sheet Page 2 for FORMNAME = COH, COHFR, CORCOH, JCOH, SCCOH, SCSPAC. File: notices.csv'
;

COPY INTO NOTICES_COVER_SHEET_2
FROM @RAW_FILES/notices.csv.gz
FILE_FORMAT = CSV_FILES;


--Table 7: Cover sheet 3
CREATE OR REPLACE TABLE COMMITTEE_PURPOSE_COVER_SHEET_3 (
    RECORD_TYPE                       VARCHAR(20)    COMMENT 'Record type code - always CVR3',
    FORM_TYPE_CD                      VARCHAR(20)    COMMENT 'TEC form used',
    REPORT_INFO_IDENT                 NUMBER(11, 0)  COMMENT 'Unique report #',
    RECEIVED_DT                       DATE           COMMENT 'Date report received by TEC',
    INFO_ONLY_FLAG                    VARCHAR(1)     COMMENT 'Superseded by other report',
    FILER_IDENT                       VARCHAR(100)   COMMENT 'Filer account #',
    FILER_TYPE_CD                     VARCHAR(30)    COMMENT 'Type of filer',
    FILER_NAME                        VARCHAR(200)   COMMENT 'Filer name',
    COMMITTEE_ACTIVITY_ID             NUMBER(11, 0)  COMMENT 'Committee activity unique identifier',
    SUBJECT_CATEGORY_CD               VARCHAR(30)    COMMENT 'Subject Category',
    SUBJECT_POSITION_CD               VARCHAR(30)    COMMENT 'Subject Position (SUPPORT, OPPOSE, ASSIST)',
    SUBJECT_DESCR                     VARCHAR(100)   COMMENT 'Subject description',
    SUBJECT_BALLOT_NUMBER             VARCHAR(10)    COMMENT 'Ballot number',
    SUBJECT_ELECTION_DT               DATE           COMMENT 'Election date',
    ACTIVITY_HOLD_OFFICE_CD           VARCHAR(30)    COMMENT 'Activity office held',
    ACTIVITY_HOLD_OFFICE_DISTRICT     VARCHAR(11)    COMMENT 'Activity office held district',
    ACTIVITY_HOLD_OFFICE_PLACE        VARCHAR(11)    COMMENT 'Activity office held place',
    ACTIVITY_HOLD_OFFICE_DESCR        VARCHAR(100)   COMMENT 'Activity office held description',
    ACTIVITY_HOLD_OFFICE_COUNTY_CD    VARCHAR(5)     COMMENT 'Activity office held county code',
    ACTIVITY_HOLD_OFFICE_COUNTY_DESCR VARCHAR(100)   COMMENT 'Activity office held county description',
    ACTIVITY_SEEK_OFFICE_CD           VARCHAR(30)    COMMENT 'Activity office sought',
    ACTIVITY_SEEK_OFFICE_DISTRICT     VARCHAR(11)    COMMENT 'Activity office sought district',
    ACTIVITY_SEEK_OFFICE_PLACE        VARCHAR(11)    COMMENT 'Activity office sought place',
    ACTIVITY_SEEK_OFFICE_DESCR        VARCHAR(100)   COMMENT 'Activity office sought description',
    ACTIVITY_SEEK_OFFICE_COUNTY_CD    VARCHAR(5)     COMMENT 'Activity office sought county code',
    ACTIVITY_SEEK_OFFICE_COUNTY_DESCR VARCHAR(100)   COMMENT 'Activity office sought county description'
) COMMENT = 'Cover Sheet 3 - Committee purpose. The committee purpose is reported at the top of Cover Sheet Page 2 for various forms. File: purpose.csv'
;

COPY INTO COMMITTEE_PURPOSE_COVER_SHEET_3
FROM @RAW_FILES/purpose.csv.gz
FILE_FORMAT = CSV_FILES;



--Table 8: Credit data
CREATE OR REPLACE TABLE CREDIT (
    RECORD_TYPE                       VARCHAR(20)       COMMENT 'Record type code - always CRED',
    FORM_TYPE_CD                      VARCHAR(20)       COMMENT 'TEC form used',
    SCHED_FORM_TYPE_CD                VARCHAR(20)       COMMENT 'TEC Schedule Used',
    REPORT_INFO_IDENT                 NUMBER(11, 0)     COMMENT 'Unique report #',
    RECEIVED_DT                       DATE              COMMENT 'Date report received by TEC',
    INFO_ONLY_FLAG                    VARCHAR(1)        COMMENT 'Superseded by other report',
    FILER_IDENT                       VARCHAR(100)      COMMENT 'Filer account #',
    FILER_TYPE_CD                     VARCHAR(30)       COMMENT 'Type of filer',
    FILER_NAME                        VARCHAR(200)      COMMENT 'Filer name',
    CREDIT_INFO_ID                    NUMBER(11, 0)     COMMENT 'Credit unique identifier',
    CREDIT_DT                         DATE              COMMENT 'Credit date',
    CREDIT_AMOUNT                     FLOAT             COMMENT 'Credit amount',
    CREDIT_DESCR                      VARCHAR(100)      COMMENT 'Credit description',
    PAYOR_PERSENT_TYPE_CD             VARCHAR(30)       COMMENT 'Type of payor name data - INDIVIDUAL or ENTITY',
    PAYOR_NAME_ORGANIZATION           VARCHAR(100)      COMMENT 'For ENTITY, the payor organization name',
    PAYOR_NAME_LAST                   VARCHAR(100)      COMMENT 'For INDIVIDUAL, the payor last name',
    PAYOR_NAME_SUFFIX_CD              VARCHAR(30)       COMMENT 'For INDIVIDUAL, the payor name suffix (e.g. JR, MD, II)',
    PAYOR_NAME_FIRST                  VARCHAR(45)       COMMENT 'For INDIVIDUAL, the payor first name',
    PAYOR_NAME_PREFIX_CD              VARCHAR(30)       COMMENT 'For INDIVIDUAL, the payor name prefix (e.g. MR, MRS, MS)',
    PAYOR_NAME_SHORT                  VARCHAR(25)       COMMENT 'For INDIVIDUAL, the payor short name (nickname)',
    PAYOR_STREET_ADDR1                VARCHAR(55)       COMMENT 'Payor street address - line 1',
    PAYOR_STREET_ADDR2                VARCHAR(55)       COMMENT 'Payor street address - line 2',
    PAYOR_STREET_CITY                 VARCHAR(30)       COMMENT 'Payor street address - city',
    PAYOR_STREET_STATE_CD             VARCHAR(2)        COMMENT 'Payor street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    PAYOR_STREET_COUNTY_CD            VARCHAR(5)        COMMENT 'Payor street address - Texas county',
    PAYOR_STREET_COUNTRY_CD           VARCHAR(3)        COMMENT 'Payor street address - country (e.g. USA, UMI, MEX, CAN)',
    PAYOR_STREET_POSTAL_CODE          VARCHAR(20)       COMMENT 'Payor street address - postal code - for USA addresses only',
    PAYOR_STREET_REGION               VARCHAR(30)       COMMENT 'Payor street address - region for country other than USA'
) COMMENT = 'Credits - Schedule K - Interest, credits, gains, refunds, and contributions returned to filer. File: credits.csv'
;

COPY INTO CREDIT
FROM @RAW_FILES/credits.csv.gz
FILE_FORMAT = CSV_FILES;



--Table 9: Debt
CREATE OR REPLACE TABLE DEBT (
    RECORD_TYPE                        VARCHAR(20)      COMMENT 'Record type code - always DEBT',
    FORM_TYPE_CD                       VARCHAR(20)      COMMENT 'TEC form used',
    SCHED_FORM_TYPE_CD                 VARCHAR(20)      COMMENT 'TEC Schedule Used',
    REPORT_INFO_IDENT                  NUMBER(11, 0)    COMMENT 'Unique report #',
    RECEIVED_DT                        DATE             COMMENT 'Date report received by TEC',
    INFO_ONLY_FLAG                     VARCHAR(1)       COMMENT 'Superseded by other report',
    FILER_IDENT                        VARCHAR(100)     COMMENT 'Filer account #',
    FILER_TYPE_CD                      VARCHAR(30)      COMMENT 'Type of filer',
    FILER_NAME                         VARCHAR(200)     COMMENT 'Filer name',
    LOAN_INFO_ID                       NUMBER(11, 0)    COMMENT 'Loan unique identifier',
    LOAN_GUARANTEED_FLAG               VARCHAR(1)       COMMENT 'Loan guaranteed indicator',
    LENDER_PERSENT_TYPE_CD             VARCHAR(30)      COMMENT 'Type of lender name data - INDIVIDUAL or ENTITY',
    LENDER_NAME_ORGANIZATION           VARCHAR(100)     COMMENT 'For ENTITY, the lender organization name',
    LENDER_NAME_LAST                   VARCHAR(100)     COMMENT 'For INDIVIDUAL, the lender last name',
    LENDER_NAME_SUFFIX_CD              VARCHAR(30)      COMMENT 'For INDIVIDUAL, the lender name suffix (e.g. JR, MD, II)',
    LENDER_NAME_FIRST                  VARCHAR(45)      COMMENT 'For INDIVIDUAL, the lender first name',
    LENDER_NAME_PREFIX_CD              VARCHAR(30)      COMMENT 'For INDIVIDUAL, the lender name prefix (e.g. MR, MRS, MS)',
    LENDER_NAME_SHORT                  VARCHAR(25)      COMMENT 'For INDIVIDUAL, the lender short name (nickname)',
    LENDER_STREET_CITY                 VARCHAR(30)      COMMENT 'Lender street address - city',
    LENDER_STREET_STATE_CD             VARCHAR(2)       COMMENT 'Lender street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    LENDER_STREET_COUNTY_CD            VARCHAR(5)       COMMENT 'Lender street address - Texas county',
    LENDER_STREET_COUNTRY_CD           VARCHAR(3)       COMMENT 'Lender street address - country (e.g. USA, UMI, MEX, CAN)',
    LENDER_STREET_POSTAL_CODE          VARCHAR(20)      COMMENT 'Lender street address - postal code - for USA addresses only',
    LENDER_STREET_REGION               VARCHAR(30)      COMMENT 'Lender street address - region for country other than USA',
    GUARANTOR_PERSENT_TYPE_CD_1          VARCHAR(30)    COMMENT 'Type of guarantor name data - INDIVIDUAL or ENTITY',
    GUARANTOR_NAME_ORGANIZATION_1        VARCHAR(100)   COMMENT 'For ENTITY, the guarantor organization name',
    GUARANTOR_NAME_LAST_1                VARCHAR(100)   COMMENT 'For INDIVIDUAL, the guarantor last name',
    GUARANTOR_NAME_SUFFIX_CD_1           VARCHAR(30)    COMMENT 'For INDIVIDUAL, the guarantor name suffix (e.g. JR, MD, II)',
    GUARANTOR_NAME_FIRST_1               VARCHAR(45)    COMMENT 'For INDIVIDUAL, the guarantor first name',
    GUARANTOR_NAME_PREFIX_CD_1           VARCHAR(30)    COMMENT 'For INDIVIDUAL, the guarantor name prefix (e.g. MR, MRS, MS)',
    GUARANTOR_NAME_SHORT_1               VARCHAR(25)    COMMENT 'For INDIVIDUAL, the guarantor short name (nickname)',
    GUARANTOR_STREET_CITY_1              VARCHAR(30)    COMMENT 'Guarantor street address - city',
    GUARANTOR_STREET_STATE_CD_1          VARCHAR(2)     COMMENT 'Guarantor street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    GUARANTOR_STREET_COUNTY_CD_1         VARCHAR(5)     COMMENT 'Guarantor street address - Texas county',
    GUARANTOR_STREET_COUNTRY_CD_1        VARCHAR(3)     COMMENT 'Guarantor street address - country (e.g. USA, UMI, MEX, CAN)',
    GUARANTOR_STREET_POSTAL_CODE_1       VARCHAR(20)    COMMENT 'Guarantor street address - postal code - for USA addresses only',
    GUARANTOR_STREET_REGION_1            VARCHAR(30)    COMMENT 'Guarantor street address - region for country other than USA',
    GUARANTOR_PERSENT_TYPE_CD_2          VARCHAR(30)    COMMENT 'Type of guarantor name data - INDIVIDUAL or ENTITY',
    GUARANTOR_NAME_ORGANIZATION_2        VARCHAR(100)   COMMENT 'For ENTITY, the guarantor organization name',
    GUARANTOR_NAME_LAST_2                VARCHAR(100)   COMMENT 'For INDIVIDUAL, the guarantor last name',
    GUARANTOR_NAME_SUFFIX_CD_2           VARCHAR(30)    COMMENT 'For INDIVIDUAL, the guarantor name suffix (e.g. JR, MD, II)',
    GUARANTOR_NAME_FIRST_2               VARCHAR(45)    COMMENT 'For INDIVIDUAL, the guarantor first name',
    GUARANTOR_NAME_PREFIX_CD_2           VARCHAR(30)    COMMENT 'For INDIVIDUAL, the guarantor name prefix (e.g. MR, MRS, MS)',
    GUARANTOR_NAME_SHORT_2               VARCHAR(25)    COMMENT 'For INDIVIDUAL, the guarantor short name (nickname)',
    GUARANTOR_STREET_CITY_2              VARCHAR(30)    COMMENT 'Guarantor street address - city',
    GUARANTOR_STREET_STATE_CD_2          VARCHAR(2)     COMMENT 'Guarantor street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    GUARANTOR_STREET_COUNTY_CD_2         VARCHAR(5)     COMMENT 'Guarantor street address - Texas county',
    GUARANTOR_STREET_COUNTRY_CD_2        VARCHAR(3)     COMMENT 'Guarantor street address - country (e.g. USA, UMI, MEX, CAN)',
    GUARANTOR_STREET_POSTAL_CODE_2       VARCHAR(20)    COMMENT 'Guarantor street address - postal code - for USA addresses only',
    GUARANTOR_STREET_REGION_2            VARCHAR(30)    COMMENT 'Guarantor street address - region for country other than USA',
    GUARANTOR_PERSENT_TYPE_CD_3          VARCHAR(30)    COMMENT 'Type of guarantor name data - INDIVIDUAL or ENTITY',
    GUARANTOR_NAME_ORGANIZATION_3        VARCHAR(100)   COMMENT 'For ENTITY, the guarantor organization name',
    GUARANTOR_NAME_LAST_3                VARCHAR(100)   COMMENT 'For INDIVIDUAL, the guarantor last name',
    GUARANTOR_NAME_SUFFIX_CD_3           VARCHAR(30)    COMMENT 'For INDIVIDUAL, the guarantor name suffix (e.g. JR, MD, II)',
    GUARANTOR_NAME_FIRST_3               VARCHAR(45)    COMMENT 'For INDIVIDUAL, the guarantor first name',
    GUARANTOR_NAME_PREFIX_CD_3           VARCHAR(30)    COMMENT 'For INDIVIDUAL, the guarantor name prefix (e.g. MR, MRS, MS)',
    GUARANTOR_NAME_SHORT_3               VARCHAR(25)    COMMENT 'For INDIVIDUAL, the guarantor short name (nickname)',
    GUARANTOR_STREET_CITY_3              VARCHAR(30)    COMMENT 'Guarantor street address - city',
    GUARANTOR_STREET_STATE_CD_3          VARCHAR(2)     COMMENT 'Guarantor street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    GUARANTOR_STREET_COUNTY_CD_3         VARCHAR(5)     COMMENT 'Guarantor street address - Texas county',
    GUARANTOR_STREET_COUNTRY_CD_3        VARCHAR(3)     COMMENT 'Guarantor street address - country (e.g. USA, UMI, MEX, CAN)',
    GUARANTOR_STREET_POSTAL_CODE_3       VARCHAR(20)    COMMENT 'Guarantor street address - postal code - for USA addresses only',
    GUARANTOR_STREET_REGION_3            VARCHAR(30)    COMMENT 'Guarantor street address - region for country other than USA',
    GUARANTOR_PERSENT_TYPE_CD_4          VARCHAR(30)    COMMENT 'Type of guarantor name data - INDIVIDUAL or ENTITY',
    GUARANTOR_NAME_ORGANIZATION_4        VARCHAR(100)   COMMENT 'For ENTITY, the guarantor organization name',
    GUARANTOR_NAME_LAST_4                VARCHAR(100)   COMMENT 'For INDIVIDUAL, the guarantor last name',
    GUARANTOR_NAME_SUFFIX_CD_4           VARCHAR(30)    COMMENT 'For INDIVIDUAL, the guarantor name suffix (e.g. JR, MD, II)',
    GUARANTOR_NAME_FIRST_4               VARCHAR(45)    COMMENT 'For INDIVIDUAL, the guarantor first name',
    GUARANTOR_NAME_PREFIX_CD_4           VARCHAR(30)    COMMENT 'For INDIVIDUAL, the guarantor name prefix (e.g. MR, MRS, MS)',
    GUARANTOR_NAME_SHORT_4               VARCHAR(25)    COMMENT 'For INDIVIDUAL, the guarantor short name (nickname)',
    GUARANTOR_STREET_CITY_4              VARCHAR(30)    COMMENT 'Guarantor street address - city',
    GUARANTOR_STREET_STATE_CD_4          VARCHAR(2)     COMMENT 'Guarantor street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    GUARANTOR_STREET_COUNTY_CD_4         VARCHAR(5)     COMMENT 'Guarantor street address - Texas county',
    GUARANTOR_STREET_COUNTRY_CD_4        VARCHAR(3)     COMMENT 'Guarantor street address - country (e.g. USA, UMI, MEX, CAN)',
    GUARANTOR_STREET_POSTAL_CODE_4       VARCHAR(20)    COMMENT 'Guarantor street address - postal code - for USA addresses only',
    GUARANTOR_STREET_REGION_4            VARCHAR(30)    COMMENT 'Guarantor street address - region for country other than USA',
    GUARANTOR_PERSENT_TYPE_CD_5          VARCHAR(30)    COMMENT 'Type of guarantor name data - INDIVIDUAL or ENTITY',
    GUARANTOR_NAME_ORGANIZATION_5        VARCHAR(100)   COMMENT 'For ENTITY, the guarantor organization name',
    GUARANTOR_NAME_LAST_5                VARCHAR(100)   COMMENT 'For INDIVIDUAL, the guarantor last name',
    GUARANTOR_NAME_SUFFIX_CD_5           VARCHAR(30)    COMMENT 'For INDIVIDUAL, the guarantor name suffix (e.g. JR, MD, II)',
    GUARANTOR_NAME_FIRST_5               VARCHAR(45)    COMMENT 'For INDIVIDUAL, the guarantor first name',
    GUARANTOR_NAME_PREFIX_CD_5           VARCHAR(30)    COMMENT 'For INDIVIDUAL, the guarantor name prefix (e.g. MR, MRS, MS)',
    GUARANTOR_NAME_SHORT_5               VARCHAR(25)    COMMENT 'For INDIVIDUAL, the guarantor short name (nickname)',
    GUARANTOR_STREET_CITY_5              VARCHAR(30)    COMMENT 'Guarantor street address - city',
    GUARANTOR_STREET_STATE_CD_5          VARCHAR(2)     COMMENT 'Guarantor street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    GUARANTOR_STREET_COUNTY_CD_5         VARCHAR(5)     COMMENT 'Guarantor street address - Texas county',
    GUARANTOR_STREET_COUNTRY_CD_5        VARCHAR(3)     COMMENT 'Guarantor street address - country (e.g. USA, UMI, MEX, CAN)',
    GUARANTOR_STREET_POSTAL_CODE_5       VARCHAR(20)    COMMENT 'Guarantor street address - postal code - for USA addresses only',
    GUARANTOR_STREET_REGION_5            VARCHAR(30)    COMMENT 'Guarantor street address - region for country other than USA'
) COMMENT = 'Debts - Schedule L - Outstanding judicial loans. File: debts.csv'
;

COPY INTO DEBT
FROM @RAW_FILES/debts.csv.gz
FILE_FORMAT = CSV_FILES;



--Table 9: 
CREATE OR REPLACE TABLE EXPENDITURES (
    RECORD_TYPE                        VARCHAR(20)      COMMENT 'Record type code - always EXPN',
    FORM_TYPE_CD                       VARCHAR(20)      COMMENT 'TEC form used',
    SCHED_FORM_TYPE_CD                 VARCHAR(20)      COMMENT 'TEC Schedule Used',
    REPORT_INFO_IDENT                  NUMBER(11, 0)    COMMENT 'Unique report #',
    RECEIVED_DT                        DATE             COMMENT 'Date report received by TEC',
    INFO_ONLY_FLAG                     VARCHAR(1)       COMMENT 'Superseded by other report',
    FILER_IDENT                        VARCHAR(100)     COMMENT 'Filer account #',
    FILER_TYPE_CD                      VARCHAR(30)      COMMENT 'Type of filer',
    FILER_NAME                         VARCHAR(200)     COMMENT 'Filer name',
    EXPEND_INFO_ID                     NUMBER(11, 0)    COMMENT 'Expenditure unique identifier',
    EXPEND_DT                          DATE             COMMENT 'Expenditure date',
    EXPEND_AMOUNT                      FLOAT            COMMENT 'Expenditure amount',
    EXPEND_DESCR                       VARCHAR(100)     COMMENT 'Expenditure description',
    EXPEND_CAT_CD                      VARCHAR(30)      COMMENT 'Expenditure category code',
    EXPEND_CAT_DESCR                   VARCHAR(100)     COMMENT 'Expenditure category description',
    ITEMIZE_FLAG                       VARCHAR(1)       COMMENT 'Y indicates that the expenditure is itemized',
    TRAVEL_FLAG                        VARCHAR(1)       COMMENT 'Y indicates that the expenditure has associated travel',
    POLITICAL_EXPEND_CD                VARCHAR(30)      COMMENT 'Political expenditure indicator',
    REIMBURSE_INTENDED_FLAG            VARCHAR(1)       COMMENT 'Reimbursement intended indicator',
    SRC_CORP_CONTRIB_FLAG              VARCHAR(1)       COMMENT 'Expenditure from corporate funds indicator',
    CAPITAL_LIVINGEXP_FLAG             VARCHAR(1)       COMMENT 'Austin living expense indicator',
    PAYEE_PERSENT_TYPE_CD              VARCHAR(30)      COMMENT 'Type of payee name data - INDIVIDUAL or ENTITY',
    PAYEE_NAME_ORGANIZATION            VARCHAR(100)     COMMENT 'For ENTITY, the payee organization name',
    PAYEE_NAME_LAST                    VARCHAR(100)     COMMENT 'For INDIVIDUAL, the payee last name',
    PAYEE_NAME_SUFFIX_CD               VARCHAR(30)      COMMENT 'For INDIVIDUAL, the payee name suffix (e.g. JR, MD, II)',
    PAYEE_NAME_FIRST                   VARCHAR(45)      COMMENT 'For INDIVIDUAL, the payee first name',
    PAYEE_NAME_PREFIX_CD               VARCHAR(30)      COMMENT 'For INDIVIDUAL, the payee name prefix (e.g. MR, MRS, MS)',
    PAYEE_NAME_SHORT                   VARCHAR(25)      COMMENT 'For INDIVIDUAL, the payee short name (nickname)',
    PAYEE_STREET_ADDR1                 VARCHAR(55)      COMMENT 'Payee street address - line 1',
    PAYEE_STREET_ADDR2                 VARCHAR(55)      COMMENT 'Payee street address - line 2',
    PAYEE_STREET_CITY                  VARCHAR(30)      COMMENT 'Payee street address - city',
    PAYEE_STREET_STATE_CD              VARCHAR(3)       COMMENT 'Payee street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    PAYEE_STREET_COUNTY_CD             VARCHAR(5)       COMMENT 'Payee street address - Texas county',
    PAYEE_STREET_COUNTRY_CD            VARCHAR(3)       COMMENT 'Payee street address - country (e.g. USA, UMI, MEX, CAN)',
    PAYEE_STREET_POSTAL_CODE           VARCHAR(20)      COMMENT 'Payee street address - postal code - for USA addresses only',
    PAYEE_STREET_REGION                VARCHAR(30)      COMMENT 'Payee street address - region for country other than USA',
    CREDIT_CARD_ISSUER                 VARCHAR(100)     COMMENT 'Financial institution issuing credit card',
    REPAYMENT_DT                       DATE             COMMENT 'Repayment date',
    SOURCE_FILE_NAME                  VARCHAR(100)      COMMENT 'Name of source file, as found in the internal stage'
) COMMENT = 'Expenditures - Schedules F/G/H/I - Expenditures from special pre-election (formerly Telegram) reports are stored separately to avoid duplicates, as they are to be re-reported on the next regular campaign finance report. Files: expend_##.csv';

COPY INTO EXPENDITURES
FROM
    (
    SELECT 
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21,
        $22,
        $23,
        $24,
        $25,
        $26,
        $27,
        $28,
        $29,
        $30,
        $31,
        $32,
        $33,
        $34,
        $35,
        $36,
        $37,
        $38,
        METADATA$FILENAME
        FROM @RAW_FILES)
FILE_FORMAT = CSV_FILES
PATTERN = 'expend_.*[.]csv[.]gz';



--Table 10: 
CREATE OR REPLACE TABLE EXPENDITURE_CATEGORIES (
    RECORD_TYPE                        VARCHAR(20)      COMMENT 'Record type code - always EXCAT',
    EXPEND_CATEGORY_CODE_VALUE         VARCHAR(30)      COMMENT 'Expenditure category code',
    EXPEND_CATEGORY_CODE_LABEL         VARCHAR(100)     COMMENT 'Expenditure category description'
) COMMENT = 'Expenditure category codes. This table stores the various categories for expenditures as defined in the system. expn_catg.csv';

COPY INTO EXPENDITURE_CATEGORIES
FROM @RAW_FILES/expn_catg.csv.gz
FILE_FORMAT = CSV_FILES;



--Table 11:
CREATE OR REPLACE TABLE FILER_INFO (
    RECORD_TYPE                        VARCHAR(20)      COMMENT 'Record type code - always FILER',
    FILER_IDENT                        VARCHAR(100)     COMMENT 'Filer account #',
    FILER_TYPE_CD                      VARCHAR(30)      COMMENT 'Type of filer',
    FILER_NAME                         VARCHAR(200)     COMMENT 'Filer name',
    UNEXPEND_CONTRIB_FILER_FLAG        VARCHAR(1)       COMMENT 'Unexpended contributions indicator',
    MODIFIED_ELECT_CYCLE_FLAG          VARCHAR(1)       COMMENT 'Modified for election cycle indicator',
    FILER_JDI_CD                       VARCHAR(30)      COMMENT 'Judicial declaration of intent code',
    COMMITTEE_STATUS_CD                VARCHAR(30)      COMMENT 'PAC filing status code',
    CTA_SEEK_OFFICE_CD                 VARCHAR(30)      COMMENT 'CTA office sought',
    CTA_SEEK_OFFICE_DISTRICT           VARCHAR(11)      COMMENT 'CTA office sought district',
    CTA_SEEK_OFFICE_PLACE              VARCHAR(11)      COMMENT 'CTA office sought place',
    CTA_SEEK_OFFICE_DESCR              VARCHAR(100)     COMMENT 'CTA office sought description',
    CTA_SEEK_OFFICE_COUNTY_CD          VARCHAR(5)       COMMENT 'CTA office sought county code',
    CTA_SEEK_OFFICE_COUNTY_DESCR       VARCHAR(100)     COMMENT 'CTA office sought county description',
    FILER_PERSENT_TYPE_CD              VARCHAR(30)      COMMENT 'Type of filer name data - INDIVIDUAL or ENTITY',
    FILER_NAME_ORGANIZATION            VARCHAR(100)     COMMENT 'For ENTITY, the filer organization name',
    FILER_NAME_LAST                    VARCHAR(100)     COMMENT 'For INDIVIDUAL, the filer last name',
    FILER_NAME_SUFFIX_CD               VARCHAR(30)      COMMENT 'For INDIVIDUAL, the filer name suffix (e.g. JR, MD, II)',
    FILER_NAME_FIRST                   VARCHAR(45)      COMMENT 'For INDIVIDUAL, the filer first name',
    FILER_NAME_PREFIX_CD               VARCHAR(30)      COMMENT 'For INDIVIDUAL, the filer name prefix (e.g. MR, MRS, MS)',
    FILER_NAME_SHORT                   VARCHAR(25)      COMMENT 'For INDIVIDUAL, the filer short name (nickname)',
    FILER_STREET_ADDR1                 VARCHAR(55)      COMMENT 'Filer street address - line 1',
    FILER_STREET_ADDR2                 VARCHAR(55)      COMMENT 'Filer street address - line 2',
    FILER_STREET_CITY                  VARCHAR(30)      COMMENT 'Filer street address - city',
    FILER_STREET_STATE_CD              VARCHAR(2)       COMMENT 'Filer street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    FILER_STREET_COUNTY_CD             VARCHAR(5)       COMMENT 'Filer street address - Texas county',
    FILER_STREET_COUNTRY_CD            VARCHAR(3)       COMMENT 'Filer street address - country (e.g. USA, UMI, MEX, CAN)',
    FILER_STREET_POSTAL_CODE           VARCHAR(20)      COMMENT 'Filer street address - postal code - for USA addresses only',
    FILER_STREET_REGION                VARCHAR(30)      COMMENT 'Filer street address - region for country other than USA',
    FILER_MAILING_ADDR1                VARCHAR(55)      COMMENT 'Filer mailing address - line 1',
    FILER_MAILING_ADDR2                VARCHAR(55)      COMMENT 'Filer mailing address - line 2',
    FILER_MAILING_CITY                 VARCHAR(30)      COMMENT 'Filer mailing address - city',
    FILER_MAILING_STATE_CD             VARCHAR(2)       COMMENT 'Filer mailing address - state code (e.g. TX, CA) - for country=USA/UMI only',
    FILER_MAILING_COUNTY_CD            VARCHAR(5)       COMMENT 'Filer mailing address - Texas county',
    FILER_MAILING_COUNTRY_CD           VARCHAR(3)       COMMENT 'Filer mailing address - country (e.g. USA, UMI, MEX, CAN)',
    FILER_MAILING_POSTAL_CODE          VARCHAR(20)      COMMENT 'Filer mailing address - postal code - USA addresses only',
    FILER_MAILING_REGION               VARCHAR(30)      COMMENT 'Filer mailing address - region for country other than USA',
    FILER_PRIMARY_USA_PHONE_FLAG       VARCHAR(1)       COMMENT 'Filer primary phone number - Y if number is a USA phone, N otherwise',
    FILER_PRIMARY_PHONE_NUMBER         VARCHAR(20)      COMMENT 'Filer primary phone number',
    FILER_PRIMARY_PHONE_EXT            VARCHAR(10)      COMMENT 'Filer primary phone extension',
    FILER_HOLD_OFFICE_CD               VARCHAR(30)      COMMENT 'Filer office held',
    FILER_HOLD_OFFICE_DISTRICT         VARCHAR(11)      COMMENT 'Filer office held district',
    FILER_HOLD_OFFICE_PLACE            VARCHAR(11)      COMMENT 'Filer office held place',
    FILER_HOLD_OFFICE_DESCR            VARCHAR(100)     COMMENT 'Filer office held description',
    FILER_HOLD_OFFICE_COUNTY_CD        VARCHAR(5)       COMMENT 'Filer office held country code',
    FILER_HOLD_OFFICE_COUNTY_DESCR     VARCHAR(100)     COMMENT 'Filer office held county description',
    filerFilerpersStatusCd             VARCHAR(30)      COMMENT 'Filer status (CURRENT, etc',
    FILER_EFF_START_DT                 DATE             COMMENT 'Filer start date',
    FILER_EFF_STOP_DT                  DATE             COMMENT 'Filer end date',
    CONTEST_FILER_SEEK_OFFICE_CD       VARCHAR(30)      COMMENT 'Filer office sought',
    CONTEST_FILER_SEEK_OFFICE_DISTRICT VARCHAR(11)      COMMENT 'Filer office sought district',
    CONTEST_FILER_SEEK_OFFICE_PLACE    VARCHAR(11)      COMMENT 'Filer office sought place',
    CONTEST_FILER_SEEK_OFFICE_DESCR    VARCHAR(100)     COMMENT 'Filer office sought description',
    CONTEST_FILER_SEEK_OFFICE_COUNTY_CD VARCHAR(5)      COMMENT 'Filer office sought county code',
    CONTEST_FILER_SEEK_OFFICE_COUNTY_DESCR VARCHAR(100) COMMENT 'Filer office sought county description',
    TREAS_PERSENT_TYPE_CD              VARCHAR(30)      COMMENT 'Type of treasurer name data - INDIVIDUAL or ENTITY',
    TREAS_NAME_ORGANIZATION            VARCHAR(100)     COMMENT 'For ENTITY, the treasurer organization name',
    TREAS_NAME_LAST                    VARCHAR(100)     COMMENT 'For INDIVIDUAL, the treasurer last name',
    TREAS_NAME_SUFFIX_CD               VARCHAR(30)      COMMENT 'For INDIVIDUAL, the treasurer name suffix (e.g. JR, MD, II)',
    TREAS_NAME_FIRST                   VARCHAR(45)      COMMENT 'For INDIVIDUAL, the treasurer first name',
    TREAS_NAME_PREFIX_CD               VARCHAR(30)      COMMENT 'For INDIVIDUAL, the treasurer name prefix (e.g. MR, MRS, MS)',
    TREAS_NAME_SHORT                   VARCHAR(25)      COMMENT 'For INDIVIDUAL, the treasurer short name (nickname)',
    TREAS_STREET_ADDR1                 VARCHAR(55)      COMMENT 'Treasurer street address - line 1',
    TREAS_STREET_ADDR2                 VARCHAR(55)      COMMENT 'Treasurer street address - line 2',
    TREAS_STREET_CITY                  VARCHAR(30)      COMMENT 'Treasurer street address - city',
    TREAS_STREET_STATE_CD              VARCHAR(2)       COMMENT 'Treasurer street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    TREAS_STREET_COUNTY_CD             VARCHAR(5)       COMMENT 'Treasurer street address - Texas county',
    TREAS_STREET_COUNTRY_CD            VARCHAR(3)       COMMENT 'Treasurer street address - country (e.g. USA, UMI, MEX, CAN)',
    TREAS_STREET_POSTAL_CODE           VARCHAR(20)      COMMENT 'Treasurer street address - postal code - for USA addresses only',
    TREAS_STREET_REGION                VARCHAR(30)      COMMENT 'Treasurer street address - region for country other than USA',
    TREAS_MAILING_ADDR1                VARCHAR(55)      COMMENT 'Treasurer mailing address - line 1',
    TREAS_MAILING_ADDR2                VARCHAR(55)      COMMENT 'Treasurer mailing address - line 2',
    TREAS_MAILING_CITY                 VARCHAR(30)      COMMENT 'Treasurer mailing address - city',
    TREAS_MAILING_STATE_CD             VARCHAR(2)       COMMENT 'Treasurer mailing address - state code (e.g. TX, CA) - for country=USA/UMI only',
    TREAS_MAILING_COUNTY_CD            VARCHAR(5)       COMMENT 'Treasurer mailing address - Texas county',
    TREAS_MAILING_COUNTRY_CD           VARCHAR(3)       COMMENT 'Treasurer mailing address - country (e.g. USA, UMI, MEX, CAN)',
    TREAS_MAILING_POSTAL_CODE          VARCHAR(20)      COMMENT 'Treasurer mailing address - postal code - for USA addresses only',
    TREAS_MAILING_REGION               VARCHAR(30)      COMMENT 'Treasurer mailing address - region for country other than USA',
    TREAS_PRIMARY_USA_PHONE_FLAG       VARCHAR(1)       COMMENT 'Treasurer primary phone number - Y if number is a USA phone, N otherwise',
    TREAS_PRIMARY_PHONE_NUMBER         VARCHAR(20)      COMMENT 'Treasurer primary phone number',
    TREAS_PRIMARY_PHONE_EXT            VARCHAR(10)      COMMENT 'Treasurer primary phone extension',
    TREAS_APPOINTOR_NAME_LAST          VARCHAR(100)     COMMENT 'For INDIVIDUAL, the treasurer last name',
    TREAS_APPOINTOR_NAME_FIRST         VARCHAR( 45)     COMMENT 'For INDIVIDUAL, the treasurer first name',
    TREAS_FILER_PERS_STATUS_CD         VARCHAR( 30)     COMMENT 'Treasurer status (CURRENT, etc)',
    TREAS_EFF_START_DT                 DATE             COMMENT 'Treasurer start date',
    TREAS_EFF_STOP_DT                  DATE             COMMENT 'Treasurer end date',
    ASST_TREAS_PERSENT_TYPE_CD         VARCHAR(30)      COMMENT 'Type of asst treasurer name data - INDIVIDUAL or ENTITY',
    ASST_TREAS_NAME_ORGANIZATION       VARCHAR(100)     COMMENT 'For ENTITY, the asst treasurer organization name',
    ASST_TREAS_NAME_LAST               VARCHAR(100)     COMMENT 'For INDIVIDUAL, the asst treasurer last name',
    ASST_TREAS_NAME_SUFFIX_CD          VARCHAR(30)      COMMENT 'For INDIVIDUAL, the asst treasurer name suffix (e.g. JR, MD, II)',
    ASST_TREAS_NAME_FIRST              VARCHAR(45)      COMMENT 'For INDIVIDUAL, the asst treasurer first name',
    ASST_TREAS_NAME_PREFIX_CD          VARCHAR(30)      COMMENT 'For INDIVIDUAL, the asst treasurer name prefix (e.g. MR, MRS, MS)',
    ASST_TREAS_NAME_SHORT              VARCHAR(25)      COMMENT 'For INDIVIDUAL, the asst treasurer short name (nickname)',
    ASST_TREAS_STREET_ADDR1            VARCHAR(55)      COMMENT 'Asst treasurer street address - line 1',
    ASST_TREAS_STREET_ADDR2            VARCHAR(55)      COMMENT 'Asst treasurer street address - line 2',
    ASST_TREAS_STREET_CITY             VARCHAR(30)      COMMENT 'Asst treasurer street address - city',
    ASST_TREAS_STREET_STATE_CD         VARCHAR(2)       COMMENT 'Asst treasurer street address - state code (e.g. TX, CA) - for country=USA/UMI onl',
    ASST_TREAS_STREET_COUNTY_CD        VARCHAR(5)       COMMENT 'Asst treasurer street address - Texas county',
    ASST_TREAS_STREET_COUNTRY_CD       VARCHAR(3)       COMMENT 'Asst treasurer street address - country (e.g. USA, UMI, MEX, CAN)',
    ASST_TREAS_STREET_POSTAL_CODE      VARCHAR(20)      COMMENT 'Asst treasurer street address - postal code - for USA addresses only',
    ASST_TREAS_STREET_REGION           VARCHAR(30)      COMMENT 'Asst treasurer street address - region for country other than US',
    ASST_TREAS_PRIMARY_USA_PHONE_FLAG  VARCHAR(1)       COMMENT 'Asst treasurer primary phone number - Y if number is a USA phone, N otherwise',
    ASST_TREAS_PRIMARY_PHONE_NUMBER    VARCHAR(20)      COMMENT 'Asst treasurer primary phone number',
    ASST_TREAS_PRIMARY_PHONE_EXT       VARCHAR(10)      COMMENT 'Asst treasurer primary phone extension',
    ASST_TREAS_APPOINTOR_NAME_LAST     VARCHAR(100)     COMMENT 'For INDIVIDUAL, the asst treasurer last name',
    ASST_TREAS_APPOINTOR_NAME_FIRST    VARCHAR(45)      COMMENT 'For INDIVIDUAL, the asst treasurer first name',
    CHAIR_PERSENT_TYPE_CD              VARCHAR(30)      COMMENT 'Type of chair name data - INDIVIDUAL or ENTITY',
    CHAIR_NAME_ORGANIZATION            VARCHAR(100)     COMMENT 'For ENTITY, the chair organization name',
    CHAIR_NAME_LAST                    VARCHAR(100)     COMMENT 'For INDIVIDUAL, the chair last name',
    CHAIR_NAME_SUFFIX_CD               VARCHAR(30)      COMMENT 'For INDIVIDUAL, the chair name suffix (e.g. JR, MD, II)',
    CHAIR_NAME_FIRST                   VARCHAR(45)      COMMENT 'For INDIVIDUAL, the chair first name',
    CHAIR_NAME_PREFIX_CD               VARCHAR(30)      COMMENT 'For INDIVIDUAL, the chair name prefix (e.g. MR, MRS, MS)',
    CHAIR_NAME_SHORT                   VARCHAR(25)      COMMENT 'For INDIVIDUAL, the chair short name (nickname)',
    CHAIR_STREET_ADDR1                 VARCHAR(55)      COMMENT 'Chair street address - line 1',
    CHAIR_STREET_ADDR2                 VARCHAR(55)      COMMENT 'Chair street address - line 2',
    CHAIR_STREET_CITY                  VARCHAR(30)      COMMENT 'Chair street address - city',
    CHAIR_STREET_STATE_CD              VARCHAR(2)       COMMENT 'Chair street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    CHAIR_STREET_COUNTY_CD             VARCHAR(5)       COMMENT 'Chair street address - Texas county',
    CHAIR_STREET_COUNTRY_CD            VARCHAR(3)       COMMENT 'Chair street address - country (e.g. USA, UMI, MEX, CAN)',
    CHAIR_STREET_POSTAL_CODE           VARCHAR(20)      COMMENT 'Chair street address - postal code - for USA addresses only',
    CHAIR_STREET_REGION                VARCHAR(30)      COMMENT 'Chair street address - region for country other than USA',
    CHAIR_MAILING_ADDR1                VARCHAR(55)      COMMENT 'Chair mailing address - line 1',
    CHAIR_MAILING_ADDR2                VARCHAR(55)      COMMENT 'Chair mailing address - line 2',
    CHAIR_MAILING_CITY                 VARCHAR(30)      COMMENT 'Chair mailing address - city',
    CHAIR_MAILING_STATE_CD             VARCHAR(2)       COMMENT 'Chair mailing address - state code (e.g. TX, CA) - for country=USA/UMI only',
    CHAIR_MAILING_COUNTY_CD            VARCHAR(5)       COMMENT 'Chair mailing address - Texas county',
    CHAIR_MAILING_COUNTRY_CD           VARCHAR(3)       COMMENT 'Chair mailing address - country (e.g. USA, UMI, MEX, CAN)',
    CHAIR_MAILING_POSTAL_CODE          VARCHAR(20)      COMMENT 'Chair mailing address - postal code - USA addresses only',
    CHAIR_MAILING_REGION               VARCHAR(30)      COMMENT 'Chair mailing address - region for country other than USA',
    CHAIR_PRIMARY_USA_PHONE_FLAG       VARCHAR(1)       COMMENT 'Chair primary phone number - Y if number is a USA phone, N otherwise',
    CHAIR_PRIMARY_PHONE_NUMBER         VARCHAR(20)      COMMENT 'Chair primary phone number',
    CHAIR_PRIMARY_PHONE_EXT            VARCHAR(10)      COMMENT 'Chair primary phone extension'
) COMMENT = 'Filer index. This table contains information about filers including names, addresses, and offices as entered by TEC staff from various sources.'
;

COPY INTO FILER_INFO
FROM @RAW_FILES/filers.csv.gz
FILE_FORMAT = CSV_FILES;



--Table 12
CREATE OR REPLACE TABLE FINAL_REPORTS (
    RECORD_TYPE                        VARCHAR(20)      COMMENT 'Record type code - always FINL',
    FORM_TYPE_CD                       VARCHAR(20)      COMMENT 'TEC form used',
    REPORT_INFO_IDENT                  NUMBER(11, 0)    COMMENT 'Unique report #',
    RECEIVED_DT                        DATE             COMMENT 'Date report received by TEC',
    INFO_ONLY_FLAG                     VARCHAR(1)       COMMENT 'Superseded by other report',
    FILER_IDENT                        VARCHAR(100)     COMMENT 'Filer account #',
    FILER_TYPE_CD                      VARCHAR(30)      COMMENT 'Type of filer',
    FILER_NAME                         VARCHAR(200)     COMMENT 'Filer name',
    FINAL_UNEXPEND_CONTRIB_FLAG        VARCHAR(1)       COMMENT 'Unexpended contributions indicator',
    FINAL_RETAINED_ASSETS_FLAG         VARCHAR(1)       COMMENT 'Retained assets indicator',
    FINAL_OFFICEHOLDER_ACK_FLAG        VARCHAR(1)       COMMENT 'Office holder ack indicator'
) COMMENT = 'Final reports indicating the closure or final status of financial activities for a specific reporting period or campaign.'
;

COPY INTO FINAL_REPORTS
FROM @RAW_FILES
FILE_FORMAT = CSV_FILES
PATTERN = 'final.*[.]csv[.]gz';



--Table 13
CREATE OR REPLACE TABLE LOANS (
    RECORD_TYPE                        VARCHAR(20)      COMMENT 'Record type code - always LOAN',
    FORM_TYPE_CD                       VARCHAR(20)      COMMENT 'TEC form used',
    SCHED_FORM_TYPE_CD                 VARCHAR(20)      COMMENT 'TEC Schedule Used',
    REPORT_INFO_IDENT                  NUMBER(11, 0)    COMMENT 'Unique report #',
    RECEIVED_DT                        DATE             COMMENT 'Date report received by TEC',
    INFO_ONLY_FLAG                     VARCHAR(1)       COMMENT 'Superseded by other report',
    FILER_IDENT                        VARCHAR(100)     COMMENT 'Filer account #',
    FILER_TYPE_CD                      VARCHAR(30)      COMMENT 'Type of filer',
    FILER_NAME                         VARCHAR(200)     COMMENT 'Filer name',
    LOAN_INFO_ID                       NUMBER(11, 0)    COMMENT 'Loan unique identifier',
    LOAN_DT                            DATE             COMMENT 'Loan date',
    LOAN_AMOUNT                        FLOAT            COMMENT 'Loan amount',
    LOAN_DESCR                         VARCHAR(100)     COMMENT 'Loan description',
    INTEREST_RATE                      VARCHAR(15)      COMMENT 'Interest rate',
    MATURITY_DT                        DATE             COMMENT 'Loan maturity date',
    COLLATERAL_FLAG                    VARCHAR(1)       COMMENT 'Collateral indicator',
    COLLATERAL_DESCR                   VARCHAR(100)     COMMENT 'Collateral description',
    LOAN_STATUS_CD                     VARCHAR(30)      COMMENT 'Loan status (1STRPT, RPTUNPAID, RPTPAID)',
    PAYMENT_MADE_FLAG                  VARCHAR(1)       COMMENT 'Payment made indicator',
    PAYMENT_AMOUNT                     FLOAT            COMMENT 'Payment amount',
    PAYMENT_SOURCE                     VARCHAR(100)     COMMENT 'Source of payment',
    LOAN_GUARANTEED_FLAG               VARCHAR(1)       COMMENT 'Loan guaranteed indicator',
    FINANCIAL_INSTITUTION_FLAG         VARCHAR(1)       COMMENT 'Financial institution indicator',
    LOAN_GUARANTEE_AMOUNT              FLOAT            COMMENT 'Loan guarantee amount',
    LENDER_PERSENT_TYPE_CD             VARCHAR(30)      COMMENT 'Type of lender name data - INDIVIDUAL or ENTITY',
    LENDER_NAME_ORGANIZATION           VARCHAR(100)     COMMENT 'For ENTITY, the lender organization name',
    LENDER_NAME_LAST                   VARCHAR(100)     COMMENT 'For INDIVIDUAL, the lender last name',
    LENDER_NAME_SUFFIX_CD              VARCHAR(30)      COMMENT 'For INDIVIDUAL, the lender name suffix (e.g. JR, MD, II)',
    LENDER_NAME_FIRST                  VARCHAR(45)      COMMENT 'For INDIVIDUAL, the lender first name',
    LENDER_NAME_PREFIX_CD              VARCHAR(30)      COMMENT 'For INDIVIDUAL, the lender name prefix (e.g. MR, MRS, MS)',
    LENDER_NAME_SHORT                  VARCHAR(25)      COMMENT 'For INDIVIDUAL, the lender short name (nickname)',
    LENDER_STREET_CITY                 VARCHAR(30)      COMMENT 'Lender street address - city',
    LENDER_STREET_STATE_CD             VARCHAR(2)       COMMENT 'Lender street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    LENDER_STREET_COUNTY_CD            VARCHAR(5)       COMMENT 'Lender street address - Texas county',
    LENDER_STREET_COUNTRY_CD           VARCHAR(3)       COMMENT 'Lender street address - country (e.g. USA, UMI, MEX, CAN)',
    LENDER_STREET_POSTAL_CODE          VARCHAR(20)      COMMENT 'Lender street address - postal code - for USA addresses only',
    LENDER_STREET_REGION               VARCHAR(30)      COMMENT 'Lender street address - region for country other than USA',
    LENDER_EMPLOYER                    VARCHAR(60)      COMMENT 'Lender employer',
    LENDER_OCCUPATION                  VARCHAR(60)      COMMENT 'Lender occupation',
    LENDER_JOB_TITLE                   VARCHAR(60)      COMMENT 'Lender job title',
    LENDER_PAC_FEIN                    VARCHAR(12)      COMMENT 'FEC ID of out-of-state PAC lender',
    LENDER_OOS_PAC_FLAG                VARCHAR(1)       COMMENT 'Indicates if lender is an out-of-state PAC',
    LENDER_LAW_FIRM_NAME               VARCHAR(60)      COMMENT 'Lender law firm name',
    LENDER_SPOUSE_LAW_FIRM_NAME        VARCHAR(60)      COMMENT 'Lender spouse law firm name',
    LENDER_PARENT1_LAW_FIRM_NAME       VARCHAR(60)      COMMENT 'Lender parent #1 law firm name',
    LENDER_PARENT2_LAW_FIRM_NAME       VARCHAR(60)      COMMENT 'Lender parent #2 law firm name',
    GUARANTOR_PERSENT_TYPE_CD_1        VARCHAR(30)      COMMENT 'Type of guarantor name data - INDIVIDUAL or ENTITY',
    GUARANTOR_NAME_ORGANIZATION_1      VARCHAR(100)     COMMENT 'For ENTITY, the guarantor organization name',
    GUARANTOR_NAME_LAST_1              VARCHAR(100)     COMMENT 'For INDIVIDUAL, the guarantor last name',
    GUARANTOR_NAME_SUFFIX_CD_1         VARCHAR(30)      COMMENT 'For INDIVIDUAL, the guarantor name suffix (e.g. JR, MD, II)',
    GUARANTOR_NAME_FIRST_1             VARCHAR(45)      COMMENT 'For INDIVIDUAL, the guarantor first name',
    GUARANTOR_NAME_PREFIX_CD_1         VARCHAR(30)      COMMENT 'For INDIVIDUAL, the guarantor name prefix (e.g. MR, MRS, MS)',
    GUARANTOR_NAME_SHORT_1             VARCHAR(25)      COMMENT 'For INDIVIDUAL, the guarantor short name (nickname)',
    GUARANTOR_STREET_CITY_1            VARCHAR(30)      COMMENT 'Guarantor street address - city',
    GUARANTOR_STREET_STATE_CD_1        VARCHAR(2)       COMMENT 'Guarantor street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    GUARANTOR_STREET_COUNTY_CD_1       VARCHAR(5)       COMMENT 'Guarantor street address - Texas county',
    GUARANTOR_STREET_COUNTRY_CD_1      VARCHAR(3)       COMMENT 'Guarantor street address - country (e.g. USA, UMI, MEX, CAN)',
    GUARANTOR_STREET_POSTAL_CODE_1     VARCHAR(20)      COMMENT 'Guarantor street address - postal code - for USA addresses only',
    GUARANTOR_STREET_REGION_1          VARCHAR(30)      COMMENT 'Guarantor street address - region for country other than USA',
    GUARANTOR_EMPLOYER_1               VARCHAR(60)      COMMENT 'Guarantor employer',
    GUARANTOR_OCCUPATION_1             VARCHAR(60)      COMMENT 'Guarantor occupation',
    GUARANTOR_JOB_TITLE_1              VARCHAR(60)      COMMENT 'Guarantor job title',
    GUARANTOR_LAWFIRM_NAME_1           VARCHAR(60)      COMMENT 'Guarantor law firm name',
    GUARANTOR_SPOUSE_LAWFIRM_NAME_1    VARCHAR(60)      COMMENT 'Guarantor spouse law firm name',
    GUARANTOR_PARENT1_LAWFIRM_NAME_1   VARCHAR(60)      COMMENT 'Guarantor parent #1 law firm name',
    GUARANTOR_PARENT2_LAWFIRM_NAME_1   VARCHAR(60)      COMMENT 'Guarantor parent #2 law firm name',
    GUARANTOR_PERSENT_TYPE_CD_2        VARCHAR(30)      COMMENT 'Type of guarantor name data - INDIVIDUAL or ENTITY',
    GUARANTOR_NAME_ORGANIZATION_2      VARCHAR(100)     COMMENT 'For ENTITY, the guarantor organization name',
    GUARANTOR_NAME_LAST_2              VARCHAR(100)     COMMENT 'For INDIVIDUAL, the guarantor last name',
    GUARANTOR_NAME_SUFFIX_CD_2         VARCHAR(30)      COMMENT 'For INDIVIDUAL, the guarantor name suffix (e.g. JR, MD, II)',
    GUARANTOR_NAME_FIRST_2             VARCHAR(45)      COMMENT 'For INDIVIDUAL, the guarantor first name',
    GUARANTOR_NAME_PREFIX_CD_2         VARCHAR(30)      COMMENT 'For INDIVIDUAL, the guarantor name prefix (e.g. MR, MRS, MS)',
    GUARANTOR_NAME_SHORT_2             VARCHAR(25)      COMMENT 'For INDIVIDUAL, the guarantor short name (nickname)',
    GUARANTOR_STREET_CITY_2            VARCHAR(30)      COMMENT 'Guarantor street address - city',
    GUARANTOR_STREET_STATE_CD_2        VARCHAR(2)       COMMENT 'Guarantor street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    GUARANTOR_STREET_COUNTY_CD_2       VARCHAR(5)       COMMENT 'Guarantor street address - Texas county',
    GUARANTOR_STREET_COUNTRY_CD_2      VARCHAR(3)       COMMENT 'Guarantor street address - country (e.g. USA, UMI, MEX, CAN)',
    GUARANTOR_STREET_POSTAL_CODE_2     VARCHAR(20)      COMMENT 'Guarantor street address - postal code - for USA addresses only',
    GUARANTOR_STREET_REGION_2          VARCHAR(30)      COMMENT 'Guarantor street address - region for country other than USA',
    GUARANTOR_EMPLOYER_2               VARCHAR(60)      COMMENT 'Guarantor employer',
    GUARANTOR_OCCUPATION_2             VARCHAR(60)      COMMENT 'Guarantor occupation',
    GUARANTOR_JOB_TITLE_2              VARCHAR(60)      COMMENT 'Guarantor job title',
    GUARANTOR_LAWFIRM_NAME_2           VARCHAR(60)      COMMENT 'Guarantor law firm name',
    GUARANTOR_SPOUSE_LAWFIRM_NAME_2    VARCHAR(60)      COMMENT 'Guarantor spouse law firm name',
    GUARANTOR_PARENT1_LAWFIRM_NAME_2   VARCHAR(60)      COMMENT 'Guarantor parent #1 law firm name',
    GUARANTOR_PARENT2_LAWFIRM_NAME_2   VARCHAR(60)      COMMENT 'Guarantor parent #2 law firm name',
    GUARANTOR_PERSENT_TYPE_CD_3        VARCHAR(30)      COMMENT 'Type of guarantor name data - INDIVIDUAL or ENTITY',
    GUARANTOR_NAME_ORGANIZATION_3      VARCHAR(100)     COMMENT 'For ENTITY, the guarantor organization name',
    GUARANTOR_NAME_LAST_3              VARCHAR(100)     COMMENT 'For INDIVIDUAL, the guarantor last name',
    GUARANTOR_NAME_SUFFIX_CD_3         VARCHAR(30)      COMMENT 'For INDIVIDUAL, the guarantor name suffix (e.g. JR, MD, II)',
    GUARANTOR_NAME_FIRST_3             VARCHAR(45)      COMMENT 'For INDIVIDUAL, the guarantor first name',
    GUARANTOR_NAME_PREFIX_CD_3         VARCHAR(30)      COMMENT 'For INDIVIDUAL, the guarantor name prefix (e.g. MR, MRS, MS)',
    GUARANTOR_NAME_SHORT_3             VARCHAR(25)      COMMENT 'For INDIVIDUAL, the guarantor short name (nickname)',
    GUARANTOR_STREET_CITY_3            VARCHAR(30)      COMMENT 'Guarantor street address - city',
    GUARANTOR_STREET_STATE_CD_3        VARCHAR(2)       COMMENT 'Guarantor street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    GUARANTOR_STREET_COUNTY_CD_3       VARCHAR(5)       COMMENT 'Guarantor street address - Texas county',
    GUARANTOR_STREET_COUNTRY_CD_3      VARCHAR(3)       COMMENT 'Guarantor street address - country (e.g. USA, UMI, MEX, CAN)',
    GUARANTOR_STREET_POSTAL_CODE_3     VARCHAR(20)      COMMENT 'Guarantor street address - postal code - for USA addresses only',
    GUARANTOR_STREET_REGION_3          VARCHAR(30)      COMMENT 'Guarantor street address - region for country other than USA',
    GUARANTOR_EMPLOYER_3               VARCHAR(60)      COMMENT 'Guarantor employer',
    GUARANTOR_OCCUPATION_3             VARCHAR(60)      COMMENT 'Guarantor occupation',
    GUARANTOR_JOB_TITLE_3              VARCHAR(60)      COMMENT 'Guarantor job title',
    GUARANTOR_LAWFIRM_NAME_3           VARCHAR(60)      COMMENT 'Guarantor law firm name',
    GUARANTOR_SPOUSE_LAWFIRM_NAME_3    VARCHAR(60)      COMMENT 'Guarantor spouse law firm name',
    GUARANTOR_PARENT1_LAWFIRM_NAME_3   VARCHAR(60)      COMMENT 'Guarantor parent #1 law firm name',
    GUARANTOR_PARENT2_LAWFIRM_NAME_3   VARCHAR(60)      COMMENT 'Guarantor parent #2 law firm name',
    GUARANTOR_PERSENT_TYPE_CD_4        VARCHAR(30)      COMMENT 'Type of guarantor name data - INDIVIDUAL or ENTITY',
    GUARANTOR_NAME_ORGANIZATION_4      VARCHAR(100)     COMMENT 'For ENTITY, the guarantor organization name',
    GUARANTOR_NAME_LAST_4              VARCHAR(100)     COMMENT 'For INDIVIDUAL, the guarantor last name',
    GUARANTOR_NAME_SUFFIX_CD_4         VARCHAR(30)      COMMENT 'For INDIVIDUAL, the guarantor name suffix (e.g. JR, MD, II)',
    GUARANTOR_NAME_FIRST_4             VARCHAR(45)      COMMENT 'For INDIVIDUAL, the guarantor first name',
    GUARANTOR_NAME_PREFIX_CD_4         VARCHAR(30)      COMMENT 'For INDIVIDUAL, the guarantor name prefix (e.g. MR, MRS, MS)',
    GUARANTOR_NAME_SHORT_4             VARCHAR(25)      COMMENT 'For INDIVIDUAL, the guarantor short name (nickname)',
    GUARANTOR_STREET_CITY_4            VARCHAR(30)      COMMENT 'Guarantor street address - city',
    GUARANTOR_STREET_STATE_CD_4        VARCHAR(2)       COMMENT 'Guarantor street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    GUARANTOR_STREET_COUNTY_CD_4       VARCHAR(5)       COMMENT 'Guarantor street address - Texas county',
    GUARANTOR_STREET_COUNTRY_CD_4      VARCHAR(3)       COMMENT 'Guarantor street address - country (e.g. USA, UMI, MEX, CAN)',
    GUARANTOR_STREET_POSTAL_CODE_4     VARCHAR(20)      COMMENT 'Guarantor street address - postal code - for USA addresses only',
    GUARANTOR_STREET_REGION_4          VARCHAR(30)      COMMENT 'Guarantor street address - region for country other than USA',
    GUARANTOR_EMPLOYER_4               VARCHAR(60)      COMMENT 'Guarantor employer',
    GUARANTOR_OCCUPATION_4             VARCHAR(60)      COMMENT 'Guarantor occupation',
    GUARANTOR_JOB_TITLE_4              VARCHAR(60)      COMMENT 'Guarantor job title',
    GUARANTOR_LAWFIRM_NAME_4           VARCHAR(60)      COMMENT 'Guarantor law firm name',
    GUARANTOR_SPOUSE_LAWFIRM_NAME_4    VARCHAR(60)      COMMENT 'Guarantor spouse law firm name',
    GUARANTOR_PARENT1_LAWFIRM_NAME_4   VARCHAR(60)      COMMENT 'Guarantor parent #1 law firm name',
    GUARANTOR_PARENT2_LAWFIRM_NAME_4   VARCHAR(60)      COMMENT 'Guarantor parent #2 law firm name',
    GUARANTOR_PERSENT_TYPE_CD_5        VARCHAR(30)      COMMENT 'Type of guarantor name data - INDIVIDUAL or ENTITY',
    GUARANTOR_NAME_ORGANIZATION_5      VARCHAR(100)     COMMENT 'For ENTITY, the guarantor organization name',
    GUARANTOR_NAME_LAST_5              VARCHAR(100)     COMMENT 'For INDIVIDUAL, the guarantor last name',
    GUARANTOR_NAME_SUFFIX_CD_5         VARCHAR(30)      COMMENT 'For INDIVIDUAL, the guarantor name suffix (e.g. JR, MD, II)',
    GUARANTOR_NAME_FIRST_5             VARCHAR(45)      COMMENT 'For INDIVIDUAL, the guarantor first name',
    GUARANTOR_NAME_PREFIX_CD_5         VARCHAR(30)      COMMENT 'For INDIVIDUAL, the guarantor name prefix (e.g. MR, MRS, MS)',
    GUARANTOR_NAME_SHORT_5             VARCHAR(25)      COMMENT 'For INDIVIDUAL, the guarantor short name (nickname)',
    GUARANTOR_STREET_CITY_5            VARCHAR(30)      COMMENT 'Guarantor street address - city',
    GUARANTOR_STREET_STATE_CD_5        VARCHAR(2)       COMMENT 'Guarantor street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    GUARANTOR_STREET_COUNTY_CD_5       VARCHAR(5)       COMMENT 'Guarantor street address - Texas county',
    GUARANTOR_STREET_COUNTRY_CD_5      VARCHAR(3)       COMMENT 'Guarantor street address - country (e.g. USA, UMI, MEX, CAN)',
    GUARANTOR_STREET_POSTAL_CODE_5     VARCHAR(20)      COMMENT 'Guarantor street address - postal code - for USA addresses only',
    GUARANTOR_STREET_REGION_5          VARCHAR(30)      COMMENT 'Guarantor street address - region for country other than USA',
    GUARANTOR_EMPLOYER_5               VARCHAR(60)      COMMENT 'Guarantor employer',
    GUARANTOR_OCCUPATION_5             VARCHAR(60)      COMMENT 'Guarantor occupation',
    GUARANTOR_JOB_TITLE_5              VARCHAR(60)      COMMENT 'Guarantor job title',
    GUARANTOR_LAWFIRM_NAME_5           VARCHAR(60)      COMMENT 'Guarantor law firm name',
    GUARANTOR_SPOUSE_LAWFIRM_NAME_5    VARCHAR(60)      COMMENT 'Guarantor spouse law firm name',
    GUARANTOR_PARENT1_LAWFIRM_NAME_5   VARCHAR(60)      COMMENT 'Guarantor parent #1 law firm name',
    GUARANTOR_PARENT2_LAWFIRM_NAME_5   VARCHAR(60)      COMMENT 'Guarantor parent #2 law firm name'
) COMMENT = 'Loans - Schedule E. This table stores information about loans, including details about lenders, guarantors, and loan terms.'
;

COPY INTO LOANS
FROM @RAW_FILES/loans.csv.gz
FILE_FORMAT = CSV_FILES;



--Table 14
CREATE OR REPLACE TABLE PLEDGES (
    RECORD_TYPE                         VARCHAR(20)     COMMENT 'Record type code - always PLEDGE',
    FORM_TYPE_CD                        VARCHAR(20)     COMMENT 'TEC form used',
    SCHED_FORM_TYPE_CD                  VARCHAR(20)     COMMENT 'TEC Schedule Used',
    REPORT_INFO_IDENT                   NUMBER(11,0)    COMMENT 'Unique report #',
    RECEIVED_DT                         DATE            COMMENT 'Date      report received by TEC',
    INFO_ONLY_FLAG                      VARCHAR(1)      COMMENT 'Superseded by other report',
    FILER_IDENT                         VARCHAR(100)    COMMENT 'Filer account #',
    FILER_TYPE_CD                       VARCHAR(30)     COMMENT 'Type of filer',
    FILER_NAME                          VARCHAR(200)    COMMENT 'Filer name',
    PLEDGE_INFO_ID                      NUMBER(11,0)    COMMENT 'Pledge unique identifier',
    PLEDGE_DT                           DATE            COMMENT 'Pledge        date',
    PLEDGE_AMOUNT                       FLOAT           COMMENT 'Pledge       amount',
    PLEDGE_DESCR                        VARCHAR(100)    COMMENT 'Pledge description',
    ITEMIZE_FLAG                        VARCHAR(1)      COMMENT 'Y indicates that the pledge is itemized',
    TRAVEL_FLAG                         VARCHAR(1)      COMMENT 'Y indicates that the pledge has associated travel',
    PLEDGER_PERSENT_TYPE_CD             VARCHAR(30)     COMMENT 'Type of pledger name data - INDIVIDUAL or ENTITY',
    PLEDGER_NAME_ORGANIZATION           VARCHAR(100)    COMMENT 'For ENTITY, the pledger organization name',
    PLEDGER_NAME_LAST                   VARCHAR(100)    COMMENT 'For INDIVIDUAL, the pledger last name',
    PLEDGER_NAME_SUFFIX_CD              VARCHAR(30)     COMMENT 'For INDIVIDUAL, the pledger name suffix (e.g. JR, MD, II)',
    PLEDGER_NAME_FIRST                  VARCHAR(45)     COMMENT 'For INDIVIDUAL, the pledger first name',
    PLEDGER_NAME_PREFIX_CD              VARCHAR(30)     COMMENT 'For INDIVIDUAL, the pledger name prefix (e.g. MR, MRS, MS)',
    PLEDGER_NAME_SHORT                  VARCHAR(25)     COMMENT 'For INDIVIDUAL, the pledger short name (nickname)',
    PLEDGER_STREET_CITY                 VARCHAR(30)     COMMENT 'Pledger street address - city',
    PLEDGER_STREET_STATE_CD             VARCHAR(2)      COMMENT 'Pledger street address - state code (e.g. TX, CA) - for country=USA/UMI only',
    PLEDGER_STREET_COUNTY_CD            VARCHAR(5)      COMMENT 'Pledger street address - Texas county',
    PLEDGER_STREET_COUNTRY_CD           VARCHAR(3)      COMMENT 'Pledger street address - country (e.g. USA, UMI, MEX, CAN)',
    PLEDGER_STREET_POSTAL_CODE          VARCHAR(20)     COMMENT 'Pledger street address - postal code - for USA addresses only',
    PLEDGER_STREET_REGION               VARCHAR(30)     COMMENT 'Pledger street address - region for country other than USA',
    PLEDGER_EMPLOYER                    VARCHAR(60)     COMMENT 'Pledger employer',
    PLEDGER_OCCUPATION                  VARCHAR(60)     COMMENT 'Pledger occupation',
    PLEDGER_JOB_TITLE                   VARCHAR(60)     COMMENT 'Pledger job title',
    PLEDGER_PAC_FEIN                     VARCHAR(12)    COMMENT 'For PAC pledger the FEIN',
    PLEDGER_OOS_PAC_FLAG                VARCHAR(1)      COMMENT 'Indicates if pledger is an out-of-state PAC',
    PLEDGER_LAW_FIRM_NAME               VARCHAR(60)     COMMENT 'Pledger law firm name',
    PLEDGER_SPOUSE_LAWFIRM_NAME         VARCHAR(60)     COMMENT 'Pledger spouse law firm name',
    PLEDGER_PARENT1_LAWFIRM_NAME        VARCHAR(60)     COMMENT 'Pledger parent #1 law firm name',
    PLEDGER_PARENT2_LAWFIRM_NAME        VARCHAR(60)     COMMENT 'Pledger parent #2 law firm name'
) COMMENT = 'Pledges - Schedule B - Pledges from special session and special pre-election (formerly Telegram) reports are stored in the file  pldg_ss and pldg_t. These records are kept separate from the pledges files to avoid creating duplicates, because they are supposed to be re-reported on the next regular campaign finance report. Files: pledges.csv'
;

COPY INTO PLEDGES
FROM @RAW_FILES/pledges.csv.gz
FILE_FORMAT = CSV_FILES;


--Table 15
CREATE OR REPLACE TABLE SPECIFIC_PURPOSE_COMMITTEES (
    RECORD_TYPE                         STRING          COMMENT 'Record type code - always SPAC',
    SPAC_FILER_IDENT                    STRING          COMMENT 'SPAC filer account #',
    SPAC_FILER_TYPE_CD                  STRING          COMMENT 'SPAC type of filer',
    SPAC_FILER_NAME                     STRING          COMMENT 'SPAC filer name',
    SPAC_FILER_NAME_SHORT               STRING          COMMENT 'SPAC acronym',
    SPAC_COMMITTEE_STATUS_CD            STRING          COMMENT 'SPAC committee status (ACTIVE, TERMINATED)',
    SPAC_TREAS_EFF_START_DT              DATE           COMMENT 'SPAC treasurer start date',
    SPAC_TREAS_EFF_STOP_DT               DATE           COMMENT 'SPAC treasurer end date',
    SPAC_POSITION_CD                    STRING          COMMENT 'SPAC position (SUPPORT, OPPOSE, ASSIST)',
    CANDIDATE_FILER_IDENT               STRING          COMMENT 'Candidate filer account #',
    CANDIDATE_FILER_TYPE_CD             STRING          COMMENT 'Candidate type of filer',
    CANDIDATE_FILER_NAME                STRING          COMMENT 'Candidate filer name',
    CANDIDATE_FILERPERS_STATUS_CD       STRING          COMMENT 'Candidate status (CURRENT, etc)',
    CANDIDATE_EFF_START_DT              DATE            COMMENT 'Candidate start date',
    CANDIDATE_EFF_STOP_DT               DATE            COMMENT 'Candidate end date',
    CANDIDATE_HOLD_OFFICE_CD            STRING          COMMENT 'Candidate office held',
    CANDIDATE_HOLD_OFFICE_DISTRICT      STRING          COMMENT 'Candidate office held district',
    CANDIDATE_HOLD_OFFICE_PLACE         STRING          COMMENT 'Candidate office held place',
    CANDIDATE_HOLD_OFFICE_DESCR         STRING          COMMENT 'Candidate office held description',
    CANDIDATE_HOLD_OFFICE_COUNTY_CD     STRING          COMMENT 'Candidate office held country code',
    CANDIDATE_HOLD_OFFICE_COUNTY_DESCR  STRING          COMMENT 'Candidate office help county description',
    CANDIDATE_SEEK_OFFICE_CD            STRING          COMMENT 'Candidate office sought',
    CANDIDATE_SEEK_OFFICE_DISTRICT      STRING          COMMENT 'Candidate office sought district',
    CANDIDATE_SEEK_OFFICE_PLACE         STRING          COMMENT 'Candidate office sought place',
    CANDIDATE_SEEK_OFFICE_DESCR         STRING          COMMENT 'Candidate office sought description',
    CANDIDATE_SEEK_OFFICE_COUNTY_CD     STRING          COMMENT 'Candidate office sought county code',
    CANDIDATE_SEEK_OFFICE_COUNTY_DESCR  STRING          COMMENT 'Candidate office sought county description',
    CTA_SEEK_OFFICE_CD                  STRING          COMMENT 'CTA office sought',
    CTA_SEEK_OFFICE_DISTRICT            STRING          COMMENT 'CTA office sought district',
    CTA_SEEK_OFFICE_PLACE               STRING          COMMENT 'CTA office sought place',
    CTA_SEEK_OFFICE_DESCR               STRING          COMMENT 'CTA office sought description',
    CTA_SEEK_OFFICE_COUNTY_CD           STRING          COMMENT 'CTA office sought county code',
    CTA_SEEK_OFFICE_COUNTY_DESCR        STRING          COMMENT 'CTA office sought county description',
    CAND_TREAS_FILERPERS_STATUS_CD       STRING         COMMENT 'Candidate treasurer status (CURRENT, etc)',
    CAND_TREAS_EFF_START_DT              DATE           COMMENT 'Candidate treasurer start date',
    CAND_TREAS_EFF_STOP_DT               DATE           COMMENT 'Candidate treasurer end date'
) COMMENT = 'Index of Specific-purpose committees. This file contains links between specific-purpose committees (FILER_TYPE = SPAC, JSPC and SCPC) and the candidates/office holders they support, oppose or assist. The information is entered by TEC staff from the paper  Form STA (treasurer appointment for a speficic- purpose committee) and amendments thereto (Form ASTA). TEC staff does not enter  links based on information from campaign finance reports. The links are not broken when the STA is terminated. File: spacs.csv'
;

COPY INTO SPECIFIC_PURPOSE_COMMITTEES
FROM @RAW_FILES/spacs.csv.gz
FILE_FORMAT = CSV_FILES;



--Table 16
CREATE OR REPLACE TABLE TRAVEL_DATA (
    RECORD_TYPE                        STRING           COMMENT 'Record type code - always TRVL',
    FORM_TYPE_CD                       STRING           COMMENT 'TEC form used',
    SCHED_FORM_TYPE_CD                 STRING           COMMENT 'TEC Schedule Used',
    REPORT_INFO_IDENT                  STRING           COMMENT 'Unique report #',
    RECEIVED_DT                        DATE             COMMENT 'Date report received by TEC',
    INFO_ONLY_FLAG                     STRING           COMMENT 'Superseded by other report',
    FILER_IDENT                        STRING           COMMENT 'Filer account #',
    FILER_TYPE_CD                      STRING           COMMENT 'Type of filer',
    FILER_NAME                         STRING           COMMENT 'Filer name',
    TRAVEL_INFO_ID                     STRING           COMMENT 'Travel unique identifier',
    PARENT_TYPE                        STRING           COMMENT 'Parent record type (CONTRIB, EXPEND, PLEDGE)',
    PARENT_ID                          STRING           COMMENT 'Parent unique identifier',
    PARENT_DT                          DATE             COMMENT 'Date of parent transaction',
    PARENT_AMOUNT                      DECIMAL(12,2)    COMMENT 'Amount of parent transaction',
    PARENT_FULL_NAME                   STRING           COMMENT 'Full name associated with parent',
    TRANSPORTATION_TYPE_CD             STRING           COMMENT 'Type of transportation (COMMAIR, PRIVAIR, etc)',
    TRANSPORTATION_TYPE_DESCR          STRING           COMMENT 'Transportation type description',
    DEPARTURE_CITY                     STRING           COMMENT 'Departure city',
    ARRIVAL_CITY                       STRING           COMMENT 'Arrival city',
    DEPARTURE_DT                       DATE             COMMENT 'Departure date',
    ARRIVAL_DT                         DATE             COMMENT 'Arrival date',
    TRAVEL_PURPOSE                     STRING           COMMENT 'Purpose of travel',
    TRAVELLER_PERSENT_TYPE_CD          STRING           COMMENT 'Type of traveller name data - INDIVIDUAL or ENTITY',
    TRAVELLER_NAME_ORGANIZATION        STRING           COMMENT 'For ENTITY, the traveller organization name',
    TRAVELLER_NAME_LAST                STRING           COMMENT 'For INDIVIDUAL, the traveller last name',
    TRAVELLER_NAME_SUFFIX_CD           STRING           COMMENT 'For INDIVIDUAL, the traveller name suffix (e.g. JR, MD, II)',
    TRAVELLER_NAME_FIRST               STRING           COMMENT 'For INDIVIDAL, the traveller first name',
    TRAVELLER_NAME_PREFIX_CD           STRING           COMMENT 'For INDIVIDUAL, the traveller name prefix (e.g. MR, MRS, MS)',
    TRAVELLER_NAME_SHORT               STRING           COMMENT 'For INDIVIDUAL, the traveller short name (nickname)'
) COMMENT = 'Travel outside the State of Texas - Schedule T - Travel records are linked to records in contribs, pledges and expenditure files through the fields parentType and parentId. They store information about in-kind contributions accepted for travel outside the  State of Texas and for expenditures made for travel outside the State of Texas. File: travel.csv'
;

COPY INTO TRAVEL_DATA
FROM @RAW_FILES/travel.csv.gz
FILE_FORMAT = CSV_FILES;
