name: campfin-env
dependencies:
  - python==3.9
  - pandas
  - geopandas
  - jupyter
  - snowflake-connector-python
  - setuptools
  - python-dotenv
  - pip
  - pip:
    - dbt-snowflake
    - snowflake-connector-python[pandas]