with EXPENDITURES AS (
    SELECT *
    FROM {{source('TEC_CAMPAIGN_FINANCE','EXPENDITURES')}}
)
SELECT 
    RECORD_TYPE,
    FORM_TYPE_CD,
    SCHED_FORM_TYPE_CD,
    REPORT_INFO_IDENT,
    RECEIVED_DT,
    INFO_ONLY_FLAG,
    FILER_IDENT,
    FILER_TYPE_CD,
    UPPER(TRIM(FILER_NAME))                     AS FILER_NAME,
    EXPEND_INFO_ID,
    EXPEND_DT,
    EXPEND_AMOUNT,
    UPPER(TRIM(EXPEND_DESCR))                   AS EXPEND_DESCR,
    EXPEND_CAT_CD,
    UPPER(TRIM(EXPEND_CAT_DESCR))               AS EXPEND_CAT_DESCR,
    ITEMIZE_FLAG,
    TRAVEL_FLAG,
    POLITICAL_EXPEND_CD,
    REIMBURSE_INTENDED_FLAG,
    SRC_CORP_CONTRIB_FLAG,
    CAPITAL_LIVINGEXP_FLAG,
    PAYEE_PERSENT_TYPE_CD,
    UPPER(
        COALESCE(
            TRIM(PAYEE_NAME_ORGANIZATION), 
            CONCAT(PAYEE_NAME_FIRST,' ',PAYEE_NAME_LAST),
            TRIM(PAYEE_NAME_LAST)
        )
    ) AS PAYEE_FULL_NAME,
    UPPER(TRIM(PAYEE_NAME_ORGANIZATION))        AS PAYEE_NAME_ORGANIZATION,
    PAYEE_NAME_PREFIX_CD,   
    UPPER(TRIM(PAYEE_NAME_FIRST))               AS PAYEE_NAME_FIRST,
    UPPER(TRIM(PAYEE_NAME_SHORT))               AS PAYEE_NAME_SHORT,
    UPPER(TRIM(PAYEE_NAME_LAST))                AS PAYEE_NAME_LAST,
    UPPER(TRIM(PAYEE_NAME_SUFFIX_CD))           AS PAYEE_NAME_SUFFIX_CD,
    UPPER(TRIM(PAYEE_STREET_ADDR1))             AS PAYEE_STREET_ADDR1,
    UPPER(TRIM(PAYEE_STREET_ADDR2))             AS PAYEE_STREET_ADDR2,
    UPPER(TRIM(PAYEE_STREET_CITY))              AS PAYEE_STREET_CITY,
    UPPER(TRIM(PAYEE_STREET_STATE_CD))          AS PAYEE_STREET_STATE_CD,
    UPPER(TRIM(PAYEE_STREET_COUNTY_CD))         AS PAYEE_STREET_COUNTY_CD,
    PAYEE_STREET_COUNTRY_CD,  
    SUBSTR(TRIM(PAYEE_STREET_POSTAL_CODE),0,5)  AS PAYEE_STREET_POSTAL_CODE,   
    PAYEE_STREET_REGION,    
    UPPER(TRIM(CREDIT_CARD_ISSUER))             AS CREDIT_CARD_ISSUER,
    REPAYMENT_DT,
    SOURCE_FILE_NAME
FROM EXPENDITURES