with ALL_RECORDS AS (
    SELECT * 
    FROM {{source("COD_CAMPAIGN_FINANCE","ALL_REPORT_RECORDS")}}
)
SELECT 
    ID,
    RECORD_ID,
    REPORT_ID,
    FILE_LINK,
    UPPER(COALESCE(
        BUSINESS_NAME,
        CONCAT(FIRST_NAME,' ',LAST_NAME)
    ))                      AS FULL_NAME,
    UPPER(FIRST_NAME)       AS FIRST_NAME,
    UPPER(LAST_NAME)        AS LAST_NAME,
    UPPER(BUSINESS_NAME)    AS BUSINESS_NAME,
    CONTACT_TYPE,
    RECORD_TYPE,
    AMOUNT,
    SCHEDULE_TYPE,
    CASE
        WHEN UPPER(CANDIDATE_NAME) = 'CANDY EVANS'         THEN 'MARY CANDACE EVANS'
        WHEN UPPER(CANDIDATE_NAME) = 'CANDACE EVANS'       THEN 'MARY CANDACE EVANS'
        WHEN UPPER(CANDIDATE_NAME) = 'MARY EVANS'          THEN 'MARY CANDACE EVANS'
        WHEN UPPER(CANDIDATE_NAME) = 'CAROLYN ARNOLD'      THEN 'CAROLYN KING ARNOLD'
        WHEN UPPER(CANDIDATE_NAME) = 'MICHAEL VALDERAS'    THEN 'GIOVANNI VALDERAS'
        WHEN UPPER(CANDIDATE_NAME) = 'TRACY HILL'          THEN 'TRACY DOTIE-HILL'
        WHEN UPPER(CANDIDATE_NAME) = 'MONICA ALONZO'       THEN 'MONICA R ALONZO' 
        WHEN UPPER(CANDIDATE_NAME) = 'RUTH TORRS'          THEN 'RUTH TORRES'
        WHEN UPPER(CANDIDATE_NAME) = 'WALTER HIGGINS'      THEN 'WALTER CHANGA HIGGINS'
        WHEN UPPER(CANDIDATE_NAME) = 'SIRRANO BALDEO'      THEN 'SIRRANO KEITH BALDEO'
        WHEN UPPER(CANDIDATE_NAME) = 'TERRY PERKINS'       THEN 'TERRANCE PERKINS'
        WHEN UPPER(CANDIDATE_NAME) = 'CHRIS CARTER'        THEN 'CHRISTOPHER CARTER'
        ELSE TRIM(UPPER(CANDIDATE_NAME))
    END AS CANDIDATE_NAME,
    ELECTION_DATE,
    TRANSACTION_DATE,
    UPPER(CONCAT(STREET,' ',CITY,' ',STATE,' ',SUBSTR(ZIPCODE,0,5))) AS FULL_ADDRESS,
    UPPER(STREET)           AS STREET,
    UPPER(CITY)             AS CITY,
    UPPER(STATE)            AS STATE,
    SUBSTR(ZIPCODE,0,5)     AS ZIPCODE,
    GEO_LOCATION_LATITUDE,
    GEO_LOCATION_LONGITUDE,
    CREATED_AT,
    UPDATED_AT,
    SOURCE_FILE_NAME,
    LOAD_DATE,
FROM ALL_RECORDS