with ALL_RECORDS AS (
    SELECT * 
    FROM {{source("COD_CAMPAIGN_FINANCE","ALL_REPORT_RECORDS")}}
)
SELECT 
    ID,
    RECORD_ID,
    REPORT_ID,
    FILE_LINK,
    CASE
        WHEN UPPER(COALESCE(BUSINESS_NAME, CONCAT(FIRST_NAME,' ',LAST_NAME))) IN ('AAGD','APARTMENT ASSOCIATION OF DALLAS','APARTMENT ASSOCIATION OF GREATER DALLAS','APARTMENT ASSOCIATION OF GREATER DALLAS-PAC','APARTMENT ASSOCIATION OF GREATER DALLAS PAC','GREATER DALLAS APARTMENT PAC','APARTMENT ASSOCIATION OF GREATER DALLAS- PAC','APPARTMENT ASSOCIATION OF GREATER DALLAS PAC','APARTMENT ASSOCIATION OF GREATER DALLAS - PAC', 'APARTMENT ASSOCIATION OF GREATER DALLAS -PAV', 'APARTMENT ASSOC OF GREATER DALLAS', 'APARTMENT ASSOC', 'GREATER DALLAS APARTMENT ASSOCIATION')  THEN 'APARTMENT ASSOCIATION OF GREATER DALLAS PAC'
        WHEN UPPER(COALESCE(BUSINESS_NAME, CONCAT(FIRST_NAME,' ',LAST_NAME))) IN ('HBA OF GREATER DALLAS HOMEPAC', 'HBA OF GREATER DALLAS HOME PAC', 'HBA GREATER DALLAS HOME PAC', 'HBA -HOMEPAC','HBA OF GREATER DALLAS PAC','HBA GREATER DALLAS HOMEPAC') THEN 'HBA OF GREATER DALLAS HOME PAC'
        WHEN UPPER(COALESCE(BUSINESS_NAME, CONCAT(FIRST_NAME,' ',LAST_NAME))) IN ('METROPLEX ASSOCIATION OF REALTORS, INC.', 'METROTEX ASSOCIATION OF REALTORS INC PAC', 'METROTEX ASSOCIATION OF REALTORS INC', 'METROTEX ASSOCIATION OF REALTORS', 'METROTEX ASSOCIATION OF REALTORS - PAC', 'TEXAS ASSOCIATION OF REALTORS METROTEX PAC', 'METROTEX ASSOCIATION OF REALTORS POLITICAL ACTION COMMITTEE', 'METROTEX ASSOC. OF REALTORS PAC') THEN 'METROTEX ASSOCIATION OF REALTORS PAC'
        WHEN UPPER(COALESCE(BUSINESS_NAME, CONCAT(FIRST_NAME,' ',LAST_NAME))) IN ('TREC', 'TREC REAL ESTATE COUNCIL', 'TEXAS REAL ESTATE COUNCIL', 'THE REAL ESTATE COUNCE POLITICAL ACTION COMMITTEE', 'THE REAL ESTATE COUNCIL PAC', 'THE REAL ESTATE COUNCIL POLITICAL ACTION COMMITTEE', 'REALESTATECOUNCIL', 'TREC PAC', 'THE REAL ESTATE COUNCIL','REAL ESTATE COUNCIL PAC') THEN 'THE REAL ESTATE COUNCIL PAC (TRECPAC)'
        WHEN UPPER(COALESCE(BUSINESS_NAME, CONCAT(FIRST_NAME,' ',LAST_NAME))) IN ('TREPAC/TEXAS ACTION OF REALTORS PAC', 'TREPAC', 'TREPAC TEXAS ASSOC OF REALTORS PAC', 'TREPAC/TEXAS ASSOCIATION OF REALTORS PAC', 'TREPAC TEXAS ASSOCIATION OF REALTORS PAC', 'TREPAC/TEXAS ASSOCIATION OF REALTORS POLITICAL ACTION COMMITTEE', 'TREPAC/TEXAS ASSOCIATION OF REALTORS POLITICAL ACTION COMMITEE', 'TREPAC TX ASSOC-REALTORS', 'TEXAS ASSOCIATION OF REALTORS PAC', 'TX. ASSOC. OF REALTORS PAC') THEN 'TEXAS ASSOCIATION OF REALTORS PAC (TREPAC)'
        WHEN UPPER(COALESCE(BUSINESS_NAME, CONCAT(FIRST_NAME,' ',LAST_NAME))) IN ('COATS ROSE P.C. PAC', 'COATS ROSE PAC', 'COATS ROSE PC PAC','COATS ROSE, P.C. POLITICAL ACTION COMMITTEE') THEN 'COATS ROSE, P.C. PAC'
        WHEN UPPER(COALESCE(BUSINESS_NAME, CONCAT(FIRST_NAME,' ',LAST_NAME))) IN ('BLACK AMERICAN FUTURE PAC','BLACK AMERICAN FUTURES PAC') THEN 'BLACK AMERICAN FUTURES PAC'
        WHEN UPPER(COALESCE(BUSINESS_NAME, CONCAT(FIRST_NAME,' ',LAST_NAME))) IN ('BLACK FIREFIGHTERS UNITED PAC', 'BLACKFIGHTERS UNITEDPAC') THEN 'BLACK FIRE FIGHTERS UNITED PAC'
        WHEN UPPER(COALESCE(BUSINESS_NAME, CONCAT(FIRST_NAME,' ',LAST_NAME))) IN ('DALLAS BLACK FIREFIGHTER RETIREE PAC', 'DALLAS BLACK FIREFIGHTER RETIREE-PAC', 'DALLAS BLACK FIREFIGHTERS RETIREE-PAC', 'DALLAS BLACK FIREFIGHTERTS RETIREE PAC') THEN 'DALLAS BLACK FIRE FIGHTERS RETIREE PAC'
        WHEN UPPER(COALESCE(BUSINESS_NAME, CONCAT(FIRST_NAME,' ',LAST_NAME))) IN ('DALLAS FIRE FIGHTERS ASSN PUBLIC SAFETY COMMITTEE','DALLAS FIREFIGHTER ASSOCIATION PUBLIC SAFETY COMMITTEE','DALLAS FIREFIGHTERS ASSOC PAC','DALLAS FIREFIGHTERS ASSOC PUBLIC SAFETY COMMITTEE','DALLAS FIREFIGHTERS ASSOCIATION - PUBLIC SAFETY COMMITTEE','DALLAS FIREFIGHTERS ASSOCIATION PAC','DALLAS FIREFIGHTERS ASSOCIATION PUBLIC SAFETY COMMITTEE','DALLAS FIREFIGHTERS ASSOCIATION PUBLIC SAFTEY COMMITTEE','DALLAS FIREFIRGHTERS ASSOCIATION PUBLIC SAFETY COMMITTEE','DALLAS FIREFIGHTERS ASSOC','DALLAS FIREFIGHTERS ASSOC.','DALLAS FIREFIGHTERS ASSOCIATION','DALLLAS FIREFIGHTERS ASSOCIATION','DALLLAS FIREFIGHTERS ASSOCIATION') THEN 'DALLAS FIRE FIGHTERS ASSOCIATION PAC'
        WHEN UPPER(COALESCE(BUSINESS_NAME, CONCAT(FIRST_NAME,' ',LAST_NAME))) IN ('DALLAS RETIRED FIREFIEGHTERS ASSOC PAC FUND','DALLAS RETIRED FIREFIGHTERS ASSN. PAC','DALLAS RETIRED FIREFIGHTERS ASSOC PAC','DALLAS RETIRED FIREFIGHTERS ASSOC PAC FUND','DALLAS RETIRED FIREFIGHTERS ASSOCIATION PAC','DALLAS RETIRED FIREFIGHTERS ASSOCIATION PAC FUND','DALLAS RETIRED FIREFIGHTERS PAC', 'DALLAS RETIRED FIREFIEGHTERS ASSOCIATIOM', 'DALLAS RETIRED FIREFIGHTERS ASSOCIATION') THEN 'DALLAS RETIRED FIRE FIGHTERS ASSOCIATION PAC'
        WHEN UPPER(COALESCE(BUSINESS_NAME, CONCAT(FIRST_NAME,' ',LAST_NAME))) IN ('DALLAS POLICE ASSOCIATION PAC','DALLAS POLICE OFFICER PAC','DALLAS POLICE OFFICERS PAC', 'DALLAS POLICE ASSOCIATION') THEN 'DALLAS POLICE ASSOCIATION PAC'
        WHEN UPPER(COALESCE(BUSINESS_NAME, CONCAT(FIRST_NAME,' ',LAST_NAME))) IN ('SOUTHWEST AIRLINES CO FREEDOM FUND PAC', 'SOUTHWEST AIRLINES CO PAC', 'SOUTHWEST AIRLINES FREEDOM FUND PAC', 'SOUTHWEST AIRLINE PAC', 'SOUTHWEST AIRLINES CO FREEDOM FUND', 'SWA FREEDOM FUND PAC') THEN 'SOUTHWEST AIRLINES CO. PAC'
        WHEN UPPER(COALESCE(BUSINESS_NAME, CONCAT(FIRST_NAME,' ',LAST_NAME))) IN ('PAC - STONEWALL DEMOCRATS OF DALLAS','STONEWALL DEMOCRATS OF DALLAS PAC','STONEWALL DEMOCRATS PAC') THEN 'STONEWALL DEMOCRATS OF DALLAS PAC'
        WHEN UPPER(COALESCE(BUSINESS_NAME, CONCAT(FIRST_NAME,' ',LAST_NAME))) IN ('TEXAS INSTRUMENTS INC POLITICAL ACTION COMMITTEE','TEXAS INSTRUMENTS INCORPORATED PAC') THEN 'TEXAS INSTRUMENTS INCORPORATED PAC'
        WHEN UPPER(COALESCE(BUSINESS_NAME, CONCAT(FIRST_NAME,' ',LAST_NAME))) IN ('SIERRA CLUB PAC','SIERRA CLUB POLITICAL COMMITTEE OF TEXAS','SIERRA POLITICAL COMMITTEE') THEN 'SIERRA CLUB PAC'
        WHEN UPPER(COALESCE(BUSINESS_NAME, CONCAT(FIRST_NAME,' ',LAST_NAME))) IN ('CWA - COPE PAC', 'CWA PAC', 'CWA POLITICAL ACTION CMTE PAC', 'CWA-COPE PAC') THEN 'COMMUNICATIONS WORKERS OF AMERICA PAC'
        ELSE UPPER(COALESCE(BUSINESS_NAME, CONCAT(FIRST_NAME,' ',LAST_NAME)))
    END                     AS FULL_NAME,
    UPPER(FIRST_NAME)       AS FIRST_NAME,
    UPPER(LAST_NAME)        AS LAST_NAME,
    UPPER(BUSINESS_NAME)    AS BUSINESS_NAME,
    CONTACT_TYPE,
    RECORD_TYPE,
    AMOUNT,
    SCHEDULE_TYPE,
    CASE
        WHEN UPPER(CANDIDATE_NAME) = 'CANDY EVANS'         THEN 'MARY CANDACE EVANS'
        WHEN UPPER(CANDIDATE_NAME) = 'CANDACE EVANS'       THEN 'MARY CANDACE EVANS'
        WHEN UPPER(CANDIDATE_NAME) = 'MARY EVANS'          THEN 'MARY CANDACE EVANS'
        WHEN UPPER(CANDIDATE_NAME) = 'CAROLYN ARNOLD'      THEN 'CAROLYN KING ARNOLD'
        WHEN UPPER(CANDIDATE_NAME) = 'MICHAEL VALDERAS'    THEN 'GIOVANNI VALDERAS'
        WHEN UPPER(CANDIDATE_NAME) = 'TRACY HILL'          THEN 'TRACY DOTIE-HILL'
        WHEN UPPER(CANDIDATE_NAME) = 'MONICA ALONZO'       THEN 'MONICA R ALONZO' 
        WHEN UPPER(CANDIDATE_NAME) = 'RUTH TORRS'          THEN 'RUTH TORRES'
        WHEN UPPER(CANDIDATE_NAME) = 'WALTER HIGGINS'      THEN 'WALTER CHANGA HIGGINS'
        WHEN UPPER(CANDIDATE_NAME) = 'SIRRANO BALDEO'      THEN 'SIRRANO KEITH BALDEO'
        WHEN UPPER(CANDIDATE_NAME) = 'TERRY PERKINS'       THEN 'TERRANCE PERKINS'
        WHEN UPPER(CANDIDATE_NAME) = 'CHRIS CARTER'        THEN 'CHRISTOPHER CARTER'
        ELSE TRIM(UPPER(CANDIDATE_NAME))
    END AS CANDIDATE_NAME,
    ELECTION_DATE,
    TRANSACTION_DATE,
    UPPER(CONCAT(STREET,' ',CITY,' ',STATE,' ',SUBSTR(ZIPCODE,0,5))) AS FULL_ADDRESS,
    UPPER(STREET)           AS STREET,
    UPPER(CITY)             AS CITY,
    UPPER(STATE)            AS STATE,
    SUBSTR(ZIPCODE,0,5)     AS ZIPCODE,
    GEO_LOCATION_LATITUDE,
    GEO_LOCATION_LONGITUDE,
    CREATED_AT,
    UPDATED_AT,
    SOURCE_FILE_NAME,
    LOAD_DATE,
FROM ALL_RECORDS