SELECT 
    ID,
    RECORD_ID,
    REPORT_ID,
    FILE_LINK,
    FULL_NAME,
    CASE
        WHEN CONTACT_TYPE = 'Contributor' THEN 'Contribution'
        WHEN CONTACT_TYPE = 'Expenditure' THEN 'Expense'
        WHEN CONTACT_TYPE = 'Lender' THEN 'Loan'
        ELSE CONTACT_TYPE
    END AS TRANSACTION_TYPE,
    RECORD_TYPE,
    AMOUNT,
    SCHEDULE_TYPE,
    CANDIDATE_NAME,
    ELECTION_DATE,
    TRANSACTION_DATE,
    CASE
        WHEN FULL_NAME IN (
            'ADAM MURPHY',
            'APARTMENT ASSOCIATION OF GREATER DALLAS PAC',
            'BRADLEY JOHNSON',
            'BRADY WOOD',
            'BRIAN ALEF',
            'CHARLES CORSON',
            'CHARLEY DORSANEO',
            'CHRIS KLEINERT',
            'CLAYTON LIKOVER',
            'COATS ROSE, P.C. PAC',
            'DANNY BAKER',
            'DAVID HELLER',
            'DON SILVERMAN',
            'ELENA LICARI',
            'ERIN GRANBERRY',
            'FRANK MIHALOPOULOS',
            'GRANT WOODRUFF',
            'HARLAN CROW',
            'HAROLD GINSBURG',
            'HBA OF GREATER DALLAS HOME PAC',
            'HUDSON HENLEY',
            'JAKE MILNER',
            'JAMES MCCORMICK',
            'JANE WEEMPE',
            'JEFF CAREY',
            'JEFFREY HOWARD',
            'JIM CHRISTON',
            'JOHN FARBES',
            'JOHN SNYDER',
            'JOSEPH DINGMAN',
            'JOSEPH PITCHFORD',
            'KATIE WURST',
            'KATY SLADE',
            'KEITH POMYKAL',
            'KIRK WILSON',
            'LELAND BURK',
            'LOU OLERIO',
            'LUCY BILLINGSLEY',
            'MARC ANDRES',
            'MATT SEGREST',
            'MATTHEW VRUGGINK',
            'MICHAEL FARRIS',
            'MIKE ABLON',
            'NICK CASSAVECHIA',
            'NICK VENGHAUS',
            'RICK PERDUE',
            'ROBERT LEE',
            'RYAN CROW',
            'STEPHEN MILLER',
            'METROTEX ASSOCIATION OF REALTORS PAC',
            'THE REAL ESTATE COUNCIL PAC (TRECPAC)',
            'TEXAS ASSOCIATION OF REALTORS PAC (TREPAC)',
            'TIM BYRNE',
            'TODD PETTY',
            'WADE ANDRES',
            'WADE JOHNS',
            'WARREN ANDRES',
            'WILLIAM ROUSE') THEN 'REAL ESTATE'
        ELSE 'OTHER'
    END AS INDUSTRY_OF_CONTRIBUTOR,
    FULL_ADDRESS,
    STREET,
    CITY,
    STATE,
    ZIPCODE,
    GEO_LOCATION_LATITUDE,
    GEO_LOCATION_LONGITUDE
FROM {{ref("int_cod_dedup_all_report_records")}}