with TOP_DONORS AS (
    SELECT PARTY_NAME
    FROM {{ref("cod_campaign_finance_records")}}
    WHERE TRANSACTION_TYPE = 'Contribution'
    GROUP BY PARTY_NAME
    ORDER BY SUM(AMOUNT) DESC
    LIMIT 1000
),
CANDIDATE_EXCLUSION AS (
    SELECT DISTINCT CANDIDATE_NAME FROM {{ref("cod_campaign_finance_records")}}
)
SELECT *
FROM {{ref("cod_campaign_finance_records")}} 
WHERE 
    PARTY_NAME NOT IN (SELECT CANDIDATE_NAME FROM CANDIDATE_EXCLUSION)
    AND PARTY_NAME IN (SELECT PARTY_NAME FROM TOP_DONORS)
    AND TRANSACTION_TYPE = 'Contribution'
