with election_contributions_6months AS (
    SELECT 
        CANDIDATE_NAME,
        SUM(AMOUNT)         AS MONEY_SPENT,
        COUNT(*)            AS NUMBER_OF_CONTRIBUTIONS
    FROM {{ref("cod_campaign_finance_records")}}
    WHERE (TRANSACTION_DATE BETWEEN '2022-11-07' AND '2023-05-06') AND TRANSACTION_TYPE = 'Expense'
    GROUP BY CANDIDATE_NAME
)
SELECT 
    ELECTION_RESULTS.ELECTION,
    ELECTION_RESULTS.DISTRICT,
    ELECTION_RESULTS.CANDIDATE_NAME,
    ELECTION_RESULTS.VOTES,
    CONTRIBUTIONS.MONEY_SPENT,
    CONTRIBUTIONS.MONEY_SPENT/ELECTION_RESULTS.VOTES AS COST_PER_VOTE,
    ELECTION_RESULTS.RESULT,
    ELECTION_RESULTS.INCUMBENT
FROM 
    CLEAN.DCED_ELECTIONS.STG_DCED__DALLAS_CITY_COUNCIL_ELECTIONS ELECTION_RESULTS
LEFT JOIN election_contributions_6months CONTRIBUTIONS
    ON ELECTION_RESULTS.CANDIDATE_NAME = CONTRIBUTIONS.CANDIDATE_NAME
WHERE ELECTION_RESULTS.ELECTION = '2023-05-06'
ORDER BY DISTRICT ASC, VOTES DESC