SELECT 
    TRANSACTION_DATE,
    FULL_NAME AS CONTRIBUTOR_NAME,
    INDUSTRY_OF_CONTRIBUTOR,
    CONCAT(CITY, ', ', STATE) AS CITY_OF_CONTRIBUTOR,
    TRANSACTION_TYPE,
    AMOUNT,
    CANDIDATE_NAME,
    FILE_LINK AS LINK_TO_REPORT
FROM {{ref("cod_all_transactions")}}
WHERE 
(TRANSACTION_DATE BETWEEN '2023-10-01' AND '2023-10-31')
AND TRANSACTION_TYPE = 'Contribution'
AND CANDIDATE_NAME = 'CHAD WEST'
ORDER BY CONTRIBUTOR_NAME