with fundraising_stats AS(
    SELECT 
        CANDIDATE_NAME,
        SUM(AMOUNT)         AS MONEY_RAISED,
        COUNT(*)            AS NUMBER_OF_CONTRIBUTIONS
    FROM {{ref("cod_all_transactions")}}
    --FROM ANALYTICS.DBT_DEV.COD_ALL_TRANSACTIONS
    WHERE 
    (TRANSACTION_DATE BETWEEN '2022-11-07' AND '2023-05-06')
    AND TRANSACTION_TYPE = 'Contribution'
    AND CANDIDATE_NAME NOT IN ('ERIC JOHNSON', 'KENDAL RICHARDSON')
    GROUP BY CANDIDATE_NAME
    ORDER BY MONEY_RAISED DESC
),
candidate_is_incumbent AS (
    SELECT 
        DISTRICT,
        CANDIDATE_NAME,
        RESULT,
        INCUMBENT AS IS_INCUMBENT,
        VOTES
    FROM {{ref("stg_dced__dallas_city_council_elections")}}
    --FROM ANALYTICS.DBT_DEV.STG_DCED__DALLAS_ELECTION_RESULTS
    WHERE ELECTION = '2023-05-06'
),
race_has_incumbents AS (
    SELECT
        ELECTION,
        DISTRICT,
        ARRAY_CONTAINS('TRUE'::VARIANT,INCUMBENT_LIST) AS RACE_HAS_INCUMBENT
    FROM 
        (SELECT 
            ELECTION,
            DISTRICT,
            ARRAY_AGG(DISTINCT INCUMBENT) INCUMBENT_LIST
        FROM {{ref('stg_dced__dallas_city_council_elections')}}
        --FROM ANALYTICS.DBT_DEV.STG_DCED__DALLAS_ELECTION_RESULTS
        WHERE ELECTION = '2023-05-06'
        GROUP BY ELECTION, DISTRICT)
)
SELECT
    B.DISTRICT,
    A.CANDIDATE_NAME,
    A.MONEY_RAISED,
    A.NUMBER_OF_CONTRIBUTIONS,
    CASE 
        WHEN B.IS_INCUMBENT = 'TRUE' THEN 'Incumbents'
        WHEN B.IS_INCUMBENT = 'FALSE' AND RACE_HAS_INCUMBENT = 'TRUE' THEN 'Challengers'
        ELSE 'Open Seat'
    END AS CANDIDATE_STATUS,
    B.RESULT AS ELECTION_RESULT,
    B.VOTES AS VOTES_RECEIVED
FROM fundraising_stats A
LEFT JOIN candidate_is_incumbent B
    ON TRIM(A.CANDIDATE_NAME) = TRIM(B.CANDIDATE_NAME)
LEFT JOIN race_has_incumbents C
    ON B.DISTRICT = C.DISTRICT
WHERE B.DISTRICT IS NOT NULL
ORDER BY DISTRICT ASC