CREATE OR REPLACE FILE FORMAT RAW.COD_CAMPAIGN_FINANCE.CSV_FILES
    TYPE = CSV 
    COMPRESSION =  GZIP
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    SKIP_BLANK_LINES = TRUE
    TRIM_SPACE = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('','NULL','null','NA','N/A','n/a','NONE','None','none')
    TIMESTAMP_FORMAT = 'YYYY-MM-DDTHH24:MI:SS.FF3Z';