with CONTRIBUTIONS_PRE_ELECTION as (
    SELECT *
    FROM {{source('TEC_CAMPAIGN_FINANCE','CONTRIBUTIONS_PRE_ELECTION')}}
)
SELECT 
    RECORD_TYPE,
    FORM_TYPE_CD,
    SCHED_FORM_TYPE_CD,
    REPORT_INFO_IDENT,
    RECEIVED_DT,
    INFO_ONLY_FLAG,
    TRIM(FILER_IDENT)                              AS FILER_IDENT,
    FILER_TYPE_CD,
    UPPER(TRIM(FILER_NAME))                        AS FILER_NAME,
    CONTRIBUTION_INFO_ID,
    CONTRIBUTION_DT,
    CONTRIBUTION_AMOUNT,
    UPPER(TRIM(CONTRIBUTION_DESCR))                AS CONTRIBUTION_DESCR,
    ITEMIZE_FLAG,
    TRAVEL_FLAG,
    CONTRIBUTOR_PERSENT_TYPE_CD,
    UPPER(
        COALESCE(
            TRIM(CONTRIBUTOR_NAME_ORGANIZATION), 
            CONCAT(TRIM(CONTRIBUTOR_NAME_FIRST),' ',TRIM(CONTRIBUTOR_NAME_LAST)),
            TRIM(CONTRIBUTOR_NAME_LAST)
        )
    ) AS CONTRIBUTOR_FULL_NAME,
    UPPER(TRIM(CONTRIBUTOR_NAME_ORGANIZATION))      AS CONTRIBUTOR_NAME_ORGANIZATION,
    UPPER(TRIM(CONTRIBUTOR_NAME_PREFIX_CD))         AS CONTRIBUTOR_NAME_PREFIX_CD,
    UPPER(TRIM(CONTRIBUTOR_NAME_FIRST))             AS CONTRIBUTOR_NAME_FIRST,
    UPPER(TRIM(CONTRIBUTOR_NAME_LAST))              AS CONTRIBUTOR_NAME_LAST,
    UPPER(TRIM(CONTRIBUTOR_NAME_SUFFIX_CD))         AS CONTRIBUTOR_NAME_SUFFIX_CD,
    UPPER(TRIM(CONTRIBUTOR_NAME_SHORT))             AS CONTRIBUTOR_NAME_SHORT,
    UPPER(TRIM(CONTRIBUTOR_STREET_CITY))            AS CONTRIBUTOR_STREET_CITY,
    UPPER(TRIM(CONTRIBUTOR_STREET_STATE_CD))        AS CONTRIBUTOR_STREET_STATE_CD,
    UPPER(TRIM(CONTRIBUTOR_STREET_COUNTY_CD))       AS CONTRIBUTOR_STREET_COUNTY_CD,
    CONTRIBUTOR_STREET_COUNTRY_CD,
    SUBSTR(TRIM(CONTRIBUTOR_STREET_POSTAL_CODE),0,5) AS CONTRIBUTOR_STREET_POSTAL_CODE,
    CONTRIBUTOR_STREET_REGION,
    UPPER(TRIM(CONTRIBUTOR_EMPLOYER))               AS CONTRIBUTOR_EMPLOYER,
    UPPER(TRIM(CONTRIBUTOR_OCCUPATION))             AS CONTRIBUTOR_OCCUPATION,
    UPPER(TRIM(CONTRIBUTOR_JOB_TITLE))              AS CONTRIBUTOR_JOB_TITLE,
    CONTRIBUTOR_PAC_FEIN,
    CONTRIBUTOR_OOS_PAC_FLAG,
    UPPER(TRIM(CONTRIBUTOR_LAWFIRM_NAME))           AS CONTRIBUTOR_LAWFIRM_NAME,
    UPPER(TRIM(CONTRIBUTOR_SPOUSE_LAWFIRM_NAME))    AS CONTRIBUTOR_SPOUSE_LAWFIRM_NAME,
    UPPER(TRIM(CONTRIBUTOR_PARENT1_LAWFIRM_NAME))   AS CONTRIBUTOR_PARENT1_LAWFIRM_NAME,
    UPPER(TRIM(CONTRIBUTOR_PARENT2_LAWFIRM_NAME))   AS CONTRIBUTOR_PARENT2_LAWFIRM_NAME,
    SOURCE_FILE_NAME
FROM CONTRIBUTIONS_PRE_ELECTION