CREATE OR REPLACE FILE FORMAT CSV_FILES
    TYPE = CSV 
    COMPRESSION =  GZIP
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    SKIP_BLANK_LINES = TRUE
    TRIM_SPACE = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'YYYYMMDD';