
CREATE OR REPLACE VIEW CAMPAIGN_FINANCE.CONTRIBUTIONS_DALLAS_COUNTY_2023 AS 
SELECT 
    CONTRIBUTIONS.RECORD_TYPE,
    CONTRIBUTIONS.FORM_TYPE_CD,
    CONTRIBUTIONS.SCHED_FORM_TYPE_CD,
    UPPER(TRIM(CANDIDATES.CHOICE_NAME)) AS FILER_NAME,
    UPPER(TRIM(FILERS.FILER_NAME_FIRST)) AS FILER_NAME_FIRST ,
    UPPER(TRIM(FILERS.FILER_NAME_LAST)) AS FILER_NAME_LAST,
    UPPER(TRIM(FILERS.FILER_NAME_SHORT)) AS FILER_NAME_SHORT,
    CANDIDATES.CONTEST_NAME             AS OFFICE_SOUGHT,
    CANDIDATES.PARTY_NAME,
    CONTRIBUTIONS.REPORT_INFO_IDENT,
    CONTRIBUTIONS.RECEIVED_DT,
    CONTRIBUTIONS.INFO_ONLY_FLAG,
    CONTRIBUTIONS.FILER_IDENT,
    CONTRIBUTIONS.FILER_TYPE_CD,
    CONTRIBUTIONS.CONTRIBUTION_INFO_ID,
    CONTRIBUTIONS.CONTRIBUTION_DT,
    CONTRIBUTIONS.CONTRIBUTION_AMOUNT,
    UPPER(TRIM(CONTRIBUTIONS.CONTRIBUTION_DESCR)) AS CONTRIBUTION_DESCR,
    CONTRIBUTIONS.ITEMIZE_FLAG,
    CONTRIBUTIONS.TRAVEL_FLAG,
    CONTRIBUTIONS.CONTRIBUTOR_PERSENT_TYPE_CD,
    UPPER(COALESCE(CONTRIBUTOR_NAME_ORGANIZATION, CONCAT(CONTRIBUTOR_NAME_FIRST,' ',CONTRIBUTOR_NAME_LAST))) AS CONTRIBUTOR_FULL_NAME,
    UPPER(TRIM(CONTRIBUTIONS.CONTRIBUTOR_NAME_ORGANIZATION)) AS CONTRIBUTOR_NAME_ORGANIZATION,
    UPPER(TRIM(CONTRIBUTIONS.CONTRIBUTOR_NAME_FIRST)) AS CONTRIBUTOR_NAME_FIRST,
    UPPER(TRIM(CONTRIBUTIONS.CONTRIBUTOR_NAME_LAST)) AS CONTRIBUTOR_NAME_LAST,
    UPPER(TRIM(CONTRIBUTIONS.CONTRIBUTOR_NAME_SUFFIX_CD)) AS CONTRIBUTOR_NAME_SUFFIX_CD,
    CONTRIBUTIONS.CONTRIBUTOR_NAME_PREFIX_CD,
    UPPER(TRIM(CONTRIBUTIONS.CONTRIBUTOR_NAME_SHORT)) AS CONTRIBUTOR_NAME_SHORT,
    UPPER(TRIM(CONTRIBUTIONS.CONTRIBUTOR_STREET_CITY)) AS CONTRIBUTOR_STREET_CITY,
    UPPER(TRIM(CONTRIBUTIONS.CONTRIBUTOR_STREET_STATE_CD)) AS CONTRIBUTOR_STREET_STATE_CD,
    UPPER(TRIM(CONTRIBUTIONS.CONTRIBUTOR_STREET_COUNTY_CD)) AS CONTRIBUTOR_STREET_COUNTY_CD,
    CONTRIBUTIONS.CONTRIBUTOR_STREET_COUNTRY_CD,
    CONTRIBUTIONS.CONTRIBUTOR_STREET_POSTAL_CODE,
    CONTRIBUTIONS.CONTRIBUTOR_STREET_REGION,
    UPPER(TRIM(CONTRIBUTIONS.CONTRIBUTOR_EMPLOYER)) AS CONTRIBUTOR_EMPLOYER,
    UPPER(TRIM(CONTRIBUTIONS.CONTRIBUTOR_OCCUPATION)) AS CONTRIBUTOR_OCCUPATION,
    CONTRIBUTIONS.CONTRIBUTOR_JOB_TITLE,
    CONTRIBUTIONS.CONTRIBUTOR_PAC_FEIN,
    CONTRIBUTIONS.CONTRIBUTOR_OOS_PAC_FLAG,
    CONTRIBUTIONS.CONTRIBUTOR_LAWFIRM_NAME,
    CONTRIBUTIONS.CONTRIBUTOR_SPOUSE_LAWFIRM_NAME,
    CONTRIBUTIONS.CONTRIBUTOR_PARENT1_LAWFIRM_NAME,
    CONTRIBUTIONS.CONTRIBUTOR_PARENT2_LAWFIRM_NAME,
    CONTRIBUTIONS.SOURCE_FILE_NAME
FROM (SELECT * FROM CONTRIBUTIONS WHERE YEAR(CONTRIBUTION_DT) >= '2023') CONTRIBUTIONS
LEFT JOIN DALLAS_COUNTY_CANDIDATES CANDIDATES
    ON CONTRIBUTIONS.FILER_IDENT = CANDIDATES.TEC_FILER_IDENT
JOIN (SELECT FILER_IDENT, FILER_NAME_FIRST, FILER_NAME_SHORT, FILER_NAME_LAST, FILER_TYPE_CD,CTA_SEEK_OFFICE_CD,CTA_SEEK_OFFICE_DISTRICT
    FROM FILER_INFO
    WHERE
    (FILER_IDENT = '00082094') OR
    (FILER_IDENT = '00088326') OR
    (FILER_IDENT = '00083877' AND CTA_SEEK_OFFICE_CD= 'PARTYCHAIRCO') OR
    (FILER_IDENT = '00082184') OR
    (FILER_IDENT = '00081730') OR
    (FILER_IDENT = '00062309') OR
    (FILER_IDENT = '00083383') OR
    (FILER_IDENT = '00083240') OR
    (FILER_IDENT = '00087886') OR
    (FILER_IDENT = '00057485') OR
    (FILER_IDENT = '00041408') OR
    (FILER_IDENT = '00088125') OR
    (FILER_IDENT = '00088247') OR
    (FILER_IDENT = '00066111') OR
    (FILER_IDENT = '00087802') OR
    (FILER_IDENT = '00058136' AND CTA_SEEK_OFFICE_CD = 'JUSTICE_SC') OR
    (FILER_IDENT = '00087764') OR
    (FILER_IDENT = '00087936') OR
    (FILER_IDENT = '00082452') OR
    (FILER_IDENT = '00080031') OR
    (FILER_IDENT = '00030098') OR
    (FILER_IDENT = '00088187') OR
    (FILER_IDENT = '00081859') OR
    (FILER_IDENT = '00081788') OR
    (FILER_IDENT = '00088232') OR
    (FILER_IDENT = '00082446') OR
    (FILER_IDENT = '00062484') OR
    (FILER_IDENT = '00055113') OR
    (FILER_IDENT = '00067708') OR
    (FILER_IDENT = '00087000') OR
    (FILER_IDENT = '00069742') OR
    (FILER_IDENT = '00085730') OR
    (FILER_IDENT = '00070992') OR
    (FILER_IDENT = '00020591') OR
    (FILER_IDENT = '00082027') OR
    (FILER_IDENT = '00088193') OR
    (FILER_IDENT = '00038111' AND CTA_SEEK_OFFICE_CD = 'JUDGE_COCA') OR
    (FILER_IDENT = '00088057') OR
    (FILER_IDENT = '00088174') OR
    (FILER_IDENT = '00082237') OR
    (FILER_IDENT = '00087349') OR
    (FILER_IDENT = '00088335') OR
    (FILER_IDENT = '00037146') OR
    (FILER_IDENT = '00086488') OR
    (FILER_IDENT = '00082026') OR
    (FILER_IDENT = '00084421') OR
    (FILER_IDENT = '00068006' AND CTA_SEEK_OFFICE_CD = 'JUSTICE_SC') OR
    (FILER_IDENT = '00026739' AND CTA_SEEK_OFFICE_CD = 'JUSTICE_SC') OR
    (FILER_IDENT = '00086370') OR
    (FILER_IDENT = '00088239') OR
    (FILER_IDENT = '00087718') OR
    (FILER_IDENT = '00088158') OR
    (FILER_IDENT = '00087226') OR
    (FILER_IDENT = '00087697') OR
    (FILER_IDENT = '00088068') OR
    (FILER_IDENT = '00087800') OR
    (FILER_IDENT = '00062111') OR
    (FILER_IDENT = '00069299') OR
    (FILER_IDENT = '00087197') OR
    (FILER_IDENT = '00088356') OR
    (FILER_IDENT = '00088227') OR
    (FILER_IDENT = '00088300') OR
    (FILER_IDENT = '00086203') OR
    (FILER_IDENT = '00087763') OR
    (FILER_IDENT = '00051444' AND CTA_SEEK_OFFICE_CD = 'JUSTICE_COA') OR
    (FILER_IDENT = '00067429') OR
    (FILER_IDENT = '00080944') OR
    (FILER_IDENT = '00069344') OR
    (FILER_IDENT = '00086397') OR
    (FILER_IDENT = '00081605') OR
    (FILER_IDENT = '00058399' AND CTA_SEEK_OFFICE_CD = 'STATESEN') OR
    (FILER_IDENT = '00067922') OR
    (FILER_IDENT = '00051772') OR
    (FILER_IDENT = '00088299') OR
    (FILER_IDENT = '00054808') OR
    (FILER_IDENT = '00069652') OR
    (FILER_IDENT = '00088388') OR
    (FILER_IDENT = '00080443') OR
    (FILER_IDENT = '00082014') OR
    (FILER_IDENT = '00051519') OR
    (FILER_IDENT = '00020990') OR
    (FILER_IDENT = '00069780') OR
    (FILER_IDENT = '00087736') OR
    (FILER_IDENT = '00026509') OR
    (FILER_IDENT = '00069606') OR
    (FILER_IDENT = '00088140') OR
    (FILER_IDENT = '00088343') OR
    (FILER_IDENT = '00069649') OR
    (FILER_IDENT = '00082440') OR
    (FILER_IDENT = '00067987') OR
    (FILER_IDENT = '00065784') OR
    (FILER_IDENT = '00085976') OR
    (FILER_IDENT = '00086182') OR
    (FILER_IDENT = '00080065') OR
    (FILER_IDENT = '00082438') OR
    (FILER_IDENT = '00088123') OR
    (FILER_IDENT = '00019811'))FILERS
ON TRIM(CONTRIBUTIONS.FILER_IDENT) = TRIM(FILERS.FILER_IDENT)
AND TRIM(CONTRIBUTIONS.FILER_TYPE_CD) = TRIM(FILERS.FILER_TYPE_CD)
;


--List of candidates from dallas county ballot. 
SELECT *
FROM FILER_INFO
WHERE 
( UPPER(FILER_NAME_FIRST) LIKE '%AICHA%'          AND UPPER(FILER_NAME_LAST) LIKE '%DAVIS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%AIMEE%'          AND UPPER(FILER_NAME_LAST) LIKE '%RAMSEY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ALLEN%'          AND UPPER(FILER_NAME_LAST) LIKE '%WEST%' AND CTA_SEEK_OFFICE_CD= 'PARTYCHAIRCO') OR
( UPPER(FILER_NAME_FIRST) LIKE '%AMANDA%'         AND UPPER(FILER_NAME_LAST) LIKE '%REICHEK%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ANA-MARIA%'      AND UPPER(FILER_NAME_LAST) LIKE '%RAMOS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ANGIE%'          AND UPPER(FILER_NAME_LAST) LIKE '%BUTTON%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ASHLEY%'         AND UPPER(FILER_NAME_LAST) LIKE '%WYSOCKI%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%AUDRA%'          AND UPPER(FILER_NAME_LAST) LIKE '%RILEY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%AVERIE%'         AND UPPER(FILER_NAME_LAST) LIKE '%BISHOP%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%BARBARA%'        AND UPPER(FILER_NAME_LAST) LIKE '%MALLORY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%BARBARA%'        AND UPPER(FILER_NAME_LAST) LIKE '%HERVEY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%BARRY%'          AND UPPER(FILER_NAME_LAST) LIKE '%WERNICK%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%WILLIAM W%'      AND UPPER(FILER_NAME_LAST) LIKE '%BURCH%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%BONNIE%'         AND UPPER(FILER_NAME_LAST) LIKE '%GOLDSTEIN%') OR
(FILER_IDENT = '00087802') OR --Brandon HAll
( UPPER(FILER_NAME_FIRST) LIKE '%BRIAN%'          AND UPPER(FILER_NAME_LAST) LIKE '%WALKER%' AND CTA_SEEK_OFFICE_CD = 'JUSTICE_SC') OR
( UPPER(FILER_NAME_FIRST) LIKE '%CASSANDRA%'      AND UPPER(FILER_NAME_LAST) = 'HERNANDEZ') OR
( UPPER(FILER_NAME_FIRST) LIKE '%CHAD%'           AND UPPER(FILER_NAME_LAST) LIKE '%CARNAHAN%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%CHAD%'           AND UPPER(FILER_NAME_LAST) LIKE '%GREEN%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%CHIKA%'          AND UPPER(FILER_NAME_LAST) LIKE '%ANYIAM%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%CHRISTI%'        AND UPPER(FILER_NAME_LAST) LIKE '%CRADDICK%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%CHRISTIE%'       AND UPPER(FILER_NAME_LAST) LIKE '%CLARK%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%CHRISTINE%'      AND UPPER(FILER_NAME_LAST) LIKE '%WEEMS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%BENJAMIN%'       AND UPPER(FILER_NAME_LAST) LIKE '%HOWELL%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%CORY%'           AND UPPER(FILER_NAME_LAST) LIKE '%CARLYLE%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%CYNTHIA%'        AND UPPER(FILER_NAME_LAST) LIKE '%BARBARE%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%DASEAN%'         AND UPPER(FILER_NAME_LAST) LIKE '%JONES%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%DAVID%'          AND UPPER(FILER_NAME_LAST) LIKE '%SCHENCK%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%DENNISE%'        AND UPPER(FILER_NAME_LAST) LIKE '%GARCIA%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%DOMINIQUE%'      AND UPPER(FILER_NAME_LAST) LIKE '%COLLINS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%EARL%'           AND UPPER(FILER_NAME_LAST) LIKE '%JACKSON%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ELIZABETH%'      AND UPPER(FILER_NAME_LAST) LIKE '%FRIZELL%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ELIZABETH%'      AND UPPER(FILER_NAME_LAST) LIKE '%GINSBERG%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%EMILY%'          AND UPPER(FILER_NAME_LAST) LIKE '%MISKEL%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ERIC%'           AND UPPER(FILER_NAME_LAST) LIKE '%MOYE%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ERIN%'           AND UPPER(FILER_NAME_LAST) LIKE '%NOWELL%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%GEORGE%'         AND UPPER(FILER_NAME_LAST) LIKE '%KING%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%GINA%'           AND UPPER(FILER_NAME_LAST) LIKE '%PARKER%' AND CTA_SEEK_OFFICE_CD = 'JUDGE_COCA') OR
( UPPER(FILER_NAME_FIRST) LIKE '%GINO%'           AND UPPER(FILER_NAME_LAST) LIKE '%ROSSINI%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%HOLLY%'          AND UPPER(FILER_NAME_LAST) LIKE '%TAYLOR%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JAMES%'          AND UPPER(FILER_NAME_LAST) LIKE '%MATLOCK%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JAMIE%'          AND UPPER(FILER_NAME_LAST) LIKE '%KOHLMANN%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JANE%'           AND UPPER(FILER_NAME_LAST) LIKE '%BLAND%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JENNIFER%'       AND UPPER(FILER_NAME_LAST) LIKE '%HAJDU%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JESSICA%'        AND UPPER(FILER_NAME_LAST) LIKE '%GONZALEZ%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JESSICA%'        AND UPPER(FILER_NAME_LAST) LIKE '%LEWIS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JAMES%'          AND UPPER(FILER_NAME_LAST) LIKE '%BLACKLOCK%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JOE%'            AND UPPER(FILER_NAME_LAST) LIKE '%POOL%' AND CTA_SEEK_OFFICE_CD = 'JUSTICE_SC') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JOHN W%'         AND UPPER(FILER_NAME_LAST) LIKE '%BRYANT%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JOHN%'           AND UPPER(FILER_NAME_LAST) LIKE '%DEVINE%' AND FILER_TYPE_CD = 'JCOH') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JOHN%'           AND UPPER(FILER_NAME_LAST) LIKE '%JUN%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JUSTICE%'        AND UPPER(FILER_NAME_LAST) LIKE '%MCFARLANE%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JUSTIN%'         AND UPPER(FILER_NAME_LAST) LIKE '%KOCH%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%KARDAL%'         AND UPPER(FILER_NAME_LAST) LIKE '%COLEMAN%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%KATHRYN%'        AND UPPER(FILER_NAME_LAST) LIKE '%RUMSEY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%KATHERINE%'      AND UPPER(FILER_NAME_LAST) LIKE '%CULBERT%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%KEN%'            AND UPPER(FILER_NAME_LAST) LIKE '%MOLBERG%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%KIM%'            AND UPPER(FILER_NAME_LAST) LIKE '%PHIPPS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%KIM%'            AND UPPER(FILER_NAME_LAST) LIKE '%COOKS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%LEAH%'           AND UPPER(FILER_NAME_LAST) LIKE '%FELDHENDLER%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%LEE%'            AND UPPER(FILER_NAME_LAST) LIKE '%FINLEY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%LINDA%'          AND UPPER(FILER_NAME_LAST) LIKE '%GARCIA%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%MATT%'           AND UPPER(FILER_NAME_LAST) LIKE '%ROSTAMI%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%MATTHEW%'        AND UPPER(FILER_NAME_LAST) LIKE '%KOLODOSKI%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%MICHELLE%'       AND UPPER(FILER_NAME_LAST) LIKE '%SLAUGHTER%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%MICHAEL G%'      AND UPPER(FILER_NAME_LAST) LIKE '%LEE%' AND CTA_SEEK_OFFICE_CD = 'JUSTICE_COA') OR
( UPPER(FILER_NAME_FIRST) LIKE '%MONICA%'         AND UPPER(FILER_NAME_LAST) LIKE '%PURDY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%MORGAN%'         AND UPPER(FILER_NAME_LAST) LIKE '%MEYER%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%NANCY%'          AND UPPER(FILER_NAME_LAST) LIKE '%MULDER%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%NATHAN%'         AND UPPER(FILER_NAME_LAST) LIKE '%JOHNSON%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%PAM%'            AND UPPER(FILER_NAME_LAST) LIKE '%LITTLE%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%PATRICIA%'       AND UPPER(FILER_NAME_LAST) LIKE '%HARDY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%PETRA%'          AND UPPER(FILER_NAME_LAST) LIKE '%REYES%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%RAFAEL%'         AND UPPER(FILER_NAME_LAST) LIKE '%ANCHIA%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%RANDALL%'        AND UPPER(FILER_NAME_LAST) LIKE '%SAROSDY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%RAYNA%'          AND UPPER(FILER_NAME_LAST) LIKE '%GLASSER%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%RHETTA%'         AND UPPER(FILER_NAME_LAST) LIKE '%BOWERS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ROBBIE%'         AND UPPER(FILER_NAME_LAST) LIKE '%PARTIDA-KIPNESS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ROSE%'           AND UPPER(FILER_NAME_LAST) LIKE '%CANNADAY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ROYCE%'          AND UPPER(FILER_NAME_LAST) LIKE '%WEST%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%SANDRA%'         AND UPPER(FILER_NAME_LAST) LIKE '%CRENSHAW%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%SCARLETT%'       AND UPPER(FILER_NAME_LAST) LIKE '%CORNWALLIS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%SHARON%'         AND UPPER(FILER_NAME_LAST) LIKE '%KELLER%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%STACI%'          AND UPPER(FILER_NAME_LAST) LIKE '%WILLIAMS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%STEPHANIE%'      AND UPPER(FILER_NAME_LAST) LIKE '%DRAPER%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%STEPHEN%'        AND UPPER(FILER_NAME_LAST) LIKE '%STANLEY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%NATHANIEL W.%'   AND UPPER(FILER_NAME_LAST) LIKE '%PARKER%' AND CTA_SEEK_OFFICE_CD = 'STATESEN') OR
( UPPER(FILER_NAME_FIRST) LIKE '%THRESA%'         AND UPPER(FILER_NAME_LAST) LIKE '%MEZA%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%TINA%'           AND UPPER(FILER_NAME_LAST) LIKE '%CLINTON%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%TONI%'           AND UPPER(FILER_NAME_LAST) LIKE '%ROSE%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%TONYA%'          AND UPPER(FILER_NAME_LAST) LIKE '%PARKER%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%TRACIE%'         AND UPPER(FILER_NAME_LAST) LIKE '%SHELBY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%VENTON%'         AND UPPER(FILER_NAME_LAST) LIKE '%JONES%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%VICTORIA%'       AND UPPER(FILER_NAME_LAST) LIKE '%NEAVE CRIADO%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%VICTORIA%'       AND UPPER(FILER_NAME_LAST) LIKE '%WALTON%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%YASMIN%'         AND UPPER(FILER_NAME_LAST) LIKE '%SIMON%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%YVONNE%'         AND UPPER(FILER_NAME_LAST) LIKE '%DAVIS%')
;



--List of candidates from dallas county ballot. 
SELECT *
FROM FILER_INFO
WHERE 
( UPPER(FILER_NAME_FIRST) LIKE '%AICHA%'          AND UPPER(FILER_NAME_LAST) LIKE '%DAVIS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%AIMEE%'          AND UPPER(FILER_NAME_LAST) LIKE '%RAMSEY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ALLEN%'          AND UPPER(FILER_NAME_LAST) LIKE '%WEST%' AND CTA_SEEK_OFFICE_CD= 'PARTYCHAIRCO') OR
( UPPER(FILER_NAME_FIRST) LIKE '%AMANDA%'         AND UPPER(FILER_NAME_LAST) LIKE '%REICHEK%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ANA-MARIA%'      AND UPPER(FILER_NAME_LAST) LIKE '%RAMOS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ANGIE%'          AND UPPER(FILER_NAME_LAST) LIKE '%BUTTON%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ASHLEY%'         AND UPPER(FILER_NAME_LAST) LIKE '%WYSOCKI%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%AUDRA%'          AND UPPER(FILER_NAME_LAST) LIKE '%RILEY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%AVERIE%'         AND UPPER(FILER_NAME_LAST) LIKE '%BISHOP%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%BARBARA%'        AND UPPER(FILER_NAME_LAST) LIKE '%MALLORY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%BARBARA%'        AND UPPER(FILER_NAME_LAST) LIKE '%HERVEY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%BARRY%'          AND UPPER(FILER_NAME_LAST) LIKE '%WERNICK%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%WILLIAM W%'      AND UPPER(FILER_NAME_LAST) LIKE '%BURCH%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%BONNIE%'         AND UPPER(FILER_NAME_LAST) LIKE '%GOLDSTEIN%') OR
(FILER_IDENT = '00087802') OR --Brandon HAll
( UPPER(FILER_NAME_FIRST) LIKE '%BRIAN%'          AND UPPER(FILER_NAME_LAST) LIKE '%WALKER%' AND CTA_SEEK_OFFICE_CD = 'JUSTICE_SC') OR
( UPPER(FILER_NAME_FIRST) LIKE '%CASSANDRA%'      AND UPPER(FILER_NAME_LAST) = 'HERNANDEZ') OR
( UPPER(FILER_NAME_FIRST) LIKE '%CHAD%'           AND UPPER(FILER_NAME_LAST) LIKE '%CARNAHAN%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%CHAD%'           AND UPPER(FILER_NAME_LAST) LIKE '%GREEN%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%CHIKA%'          AND UPPER(FILER_NAME_LAST) LIKE '%ANYIAM%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%CHRISTI%'        AND UPPER(FILER_NAME_LAST) LIKE '%CRADDICK%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%CHRISTIE%'       AND UPPER(FILER_NAME_LAST) LIKE '%CLARK%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%CHRISTINE%'      AND UPPER(FILER_NAME_LAST) LIKE '%WEEMS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%BENJAMIN%'       AND UPPER(FILER_NAME_LAST) LIKE '%HOWELL%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%CORY%'           AND UPPER(FILER_NAME_LAST) LIKE '%CARLYLE%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%CYNTHIA%'        AND UPPER(FILER_NAME_LAST) LIKE '%BARBARE%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%DASEAN%'         AND UPPER(FILER_NAME_LAST) LIKE '%JONES%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%DAVID%'          AND UPPER(FILER_NAME_LAST) LIKE '%SCHENCK%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%DENNISE%'        AND UPPER(FILER_NAME_LAST) LIKE '%GARCIA%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%DOMINIQUE%'      AND UPPER(FILER_NAME_LAST) LIKE '%COLLINS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%EARL%'           AND UPPER(FILER_NAME_LAST) LIKE '%JACKSON%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ELIZABETH%'      AND UPPER(FILER_NAME_LAST) LIKE '%FRIZELL%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ELIZABETH%'      AND UPPER(FILER_NAME_LAST) LIKE '%GINSBERG%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%EMILY%'          AND UPPER(FILER_NAME_LAST) LIKE '%MISKEL%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ERIC%'           AND UPPER(FILER_NAME_LAST) LIKE '%MOYE%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ERIN%'           AND UPPER(FILER_NAME_LAST) LIKE '%NOWELL%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%GEORGE%'         AND UPPER(FILER_NAME_LAST) LIKE '%KING%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%GINA%'           AND UPPER(FILER_NAME_LAST) LIKE '%PARKER%' AND CTA_SEEK_OFFICE_CD = 'JUDGE_COCA') OR
( UPPER(FILER_NAME_FIRST) LIKE '%GINO%'           AND UPPER(FILER_NAME_LAST) LIKE '%ROSSINI%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%HOLLY%'          AND UPPER(FILER_NAME_LAST) LIKE '%TAYLOR%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JAMES%'          AND UPPER(FILER_NAME_LAST) LIKE '%MATLOCK%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JAMIE%'          AND UPPER(FILER_NAME_LAST) LIKE '%KOHLMANN%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JANE%'           AND UPPER(FILER_NAME_LAST) LIKE '%BLAND%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JENNIFER%'       AND UPPER(FILER_NAME_LAST) LIKE '%HAJDU%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JESSICA%'        AND UPPER(FILER_NAME_LAST) LIKE '%GONZALEZ%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JESSICA%'        AND UPPER(FILER_NAME_LAST) LIKE '%LEWIS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JAMES%'          AND UPPER(FILER_NAME_LAST) LIKE '%BLACKLOCK%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JOE%'            AND UPPER(FILER_NAME_LAST) LIKE '%POOL%' AND CTA_SEEK_OFFICE_CD = 'JUSTICE_SC') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JOHN W%'         AND UPPER(FILER_NAME_LAST) LIKE '%BRYANT%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JOHN%'           AND UPPER(FILER_NAME_LAST) LIKE '%DEVINE%' AND FILER_TYPE_CD = 'JCOH') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JOHN%'           AND UPPER(FILER_NAME_LAST) LIKE '%JUN%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JUSTICE%'        AND UPPER(FILER_NAME_LAST) LIKE '%MCFARLANE%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%JUSTIN%'         AND UPPER(FILER_NAME_LAST) LIKE '%KOCH%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%KARDAL%'         AND UPPER(FILER_NAME_LAST) LIKE '%COLEMAN%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%KATHRYN%'        AND UPPER(FILER_NAME_LAST) LIKE '%RUMSEY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%KATHERINE%'      AND UPPER(FILER_NAME_LAST) LIKE '%CULBERT%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%KEN%'            AND UPPER(FILER_NAME_LAST) LIKE '%MOLBERG%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%KIM%'            AND UPPER(FILER_NAME_LAST) LIKE '%PHIPPS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%KIM%'            AND UPPER(FILER_NAME_LAST) LIKE '%COOKS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%LEAH%'           AND UPPER(FILER_NAME_LAST) LIKE '%FELDHENDLER%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%LEE%'            AND UPPER(FILER_NAME_LAST) LIKE '%FINLEY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%LINDA%'          AND UPPER(FILER_NAME_LAST) LIKE '%GARCIA%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%MATT%'           AND UPPER(FILER_NAME_LAST) LIKE '%ROSTAMI%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%MATTHEW%'        AND UPPER(FILER_NAME_LAST) LIKE '%KOLODOSKI%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%MICHELLE%'       AND UPPER(FILER_NAME_LAST) LIKE '%SLAUGHTER%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%MICHAEL G%'      AND UPPER(FILER_NAME_LAST) LIKE '%LEE%' AND CTA_SEEK_OFFICE_CD = 'JUSTICE_COA') OR
( UPPER(FILER_NAME_FIRST) LIKE '%MONICA%'         AND UPPER(FILER_NAME_LAST) LIKE '%PURDY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%MORGAN%'         AND UPPER(FILER_NAME_LAST) LIKE '%MEYER%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%NANCY%'          AND UPPER(FILER_NAME_LAST) LIKE '%MULDER%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%NATHAN%'         AND UPPER(FILER_NAME_LAST) LIKE '%JOHNSON%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%PAM%'            AND UPPER(FILER_NAME_LAST) LIKE '%LITTLE%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%PATRICIA%'       AND UPPER(FILER_NAME_LAST) LIKE '%HARDY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%PETRA%'          AND UPPER(FILER_NAME_LAST) LIKE '%REYES%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%RAFAEL%'         AND UPPER(FILER_NAME_LAST) LIKE '%ANCHIA%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%RANDALL%'        AND UPPER(FILER_NAME_LAST) LIKE '%SAROSDY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%RAYNA%'          AND UPPER(FILER_NAME_LAST) LIKE '%GLASSER%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%RHETTA%'         AND UPPER(FILER_NAME_LAST) LIKE '%BOWERS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ROBBIE%'         AND UPPER(FILER_NAME_LAST) LIKE '%PARTIDA-KIPNESS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ROSE%'           AND UPPER(FILER_NAME_LAST) LIKE '%CANNADAY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%ROYCE%'          AND UPPER(FILER_NAME_LAST) LIKE '%WEST%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%SANDRA%'         AND UPPER(FILER_NAME_LAST) LIKE '%CRENSHAW%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%SCARLETT%'       AND UPPER(FILER_NAME_LAST) LIKE '%CORNWALLIS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%SHARON%'         AND UPPER(FILER_NAME_LAST) LIKE '%KELLER%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%STACI%'          AND UPPER(FILER_NAME_LAST) LIKE '%WILLIAMS%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%STEPHANIE%'      AND UPPER(FILER_NAME_LAST) LIKE '%DRAPER%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%STEPHEN%'        AND UPPER(FILER_NAME_LAST) LIKE '%STANLEY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%NATHANIEL W.%'   AND UPPER(FILER_NAME_LAST) LIKE '%PARKER%' AND CTA_SEEK_OFFICE_CD = 'STATESEN') OR
( UPPER(FILER_NAME_FIRST) LIKE '%THRESA%'         AND UPPER(FILER_NAME_LAST) LIKE '%MEZA%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%TINA%'           AND UPPER(FILER_NAME_LAST) LIKE '%CLINTON%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%TONI%'           AND UPPER(FILER_NAME_LAST) LIKE '%ROSE%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%TONYA%'          AND UPPER(FILER_NAME_LAST) LIKE '%PARKER%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%TRACIE%'         AND UPPER(FILER_NAME_LAST) LIKE '%SHELBY%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%VENTON%'         AND UPPER(FILER_NAME_LAST) LIKE '%JONES%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%VICTORIA%'       AND UPPER(FILER_NAME_LAST) LIKE '%NEAVE CRIADO%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%VICTORIA%'       AND UPPER(FILER_NAME_LAST) LIKE '%WALTON%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%YASMIN%'         AND UPPER(FILER_NAME_LAST) LIKE '%SIMON%') OR
( UPPER(FILER_NAME_FIRST) LIKE '%YVONNE%'         AND UPPER(FILER_NAME_LAST) LIKE '%DAVIS%')
ORDER BY TRIM(FILER_NAME_FIRST);
